### ISSUE TITLE
error in processing station1_xyz_intensity_rgb.ply during testing on Semantic3D

### ISSUE THREAD

**Issue by azuki-miho** [HuguesTHOMAS/KPConv#100]
After data processing on Semantic3D, station1_xyz_intensity_rgb.ply appears in the path Data/Semantic3D/ply_full/reduced-8. However, when I run the test_any_model.py, Keyerror occurs during running  dataset.ascii_files[cloud_name], because station1_xyz_intensity_rgb.ply appears in the corresponding path but there are no matching keys in dataset.ascii_files in datasets/Semantic3D.py.

**Comment by HuguesTHOMAS** [comment]
This is very strange, first, their should not be a `station1_xyz_intensity_rgb.ply` file. It seems you might have modified the file names when downloading them from the official website. Can you make sure you run the code with the original point cloud names, for both training and test?

**Comment by azuki-miho** [comment]
I find the problem, the extracted files from the downloaded .7z file have something wrong in naming. I need to rename station1_xyz_intensity_rgb.txt as neugasse_station1_xyz_intensity_rgb.txt after extraction
