### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by MilesZhao** [HuguesTHOMAS/KPConv#101]
Hi Hugues,

Thanks for the excellent work!

Recently, I was trying to run classification job on ModelNet40 dataset. (I am using tf1.14). There is always a error popped up as shown in the title when calling "tf_batch_neighbors_module.batch_ordered_neighbors". Could you share some idea how to fix this?

You mentioned you found bugs when using tf 1.13. I am sure what happened to me is the same as you found tf 1.13.

**Comment by HuguesTHOMAS** [comment]
Could you try to print the input of the `tf_batch_neighbors_module.batch_ordered_neighbors`? At this point:

https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/datasets/common.py#L69-L70

You can print the shape and dtype of the input tensors and see if there is something wrong with them when the segfault happens.

Best,
Hugues

**Comment by MilesZhao** [comment]
Thanks for the reply!

I compiled tf1.12 and now everything works fine.

**Comment by whuhxb** [comment]
@MilesZhao 
Hi, 
   I have complied tf1.12, and it only works on CPU to complie tf_custom_ops and cpp_wrappers. But, when I complie tf1.12 with GPU, the compliation of tf_custom_ops and cpp_wrappers dumps. I have no idea of how to solve this? Does the code run on CPU?  Could it be run on GPU? Thanks.
