### ISSUE TITLE
about online test on semanti3d

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#106]
What is the file format of the prediction results that need to be uploaded when testing the semantic3D dataset online?Can you show it in detail?The website description is very unclear. looking forward to your reply.

**Comment by HuguesTHOMAS** [comment]
Just save the prediction in a txt file, one line per point. Look at the code that does it here:
https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/utils/tester.py#L799-L804

**Comment by longmalongma** [comment]
> Just save the prediction in a txt file, one line per point. Look at the code that does it here:
> https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/utils/tester.py#L799-L804

Can you provide the format of the file you submitted for the semantic3D test online?What documents are required for semantic3d reduced-8?

**Comment by cystal-lili** [comment]
I want to know what does the cloud_[:-4} mean? Thank you

**Comment by HuguesTHOMAS** [comment]
It just means that I rename the cloud from `XXXXX.ply` to `XXXXX.txt`. But in the case of reduced-8, this line of code is not used, the name of the ascii file is defined by `dataset.ascii_files` here:

https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/datasets/Semantic3D.py#L148-L149

**Comment by cystal-lili** [comment]
Hello, I am very happy to receive your reply. Thank you for your code. I want to experiment with a new model based on your model, but it’s so difficult. Any suggestions? Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hugues THOMAS"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 晚上10:30
收件人: "HuguesTHOMAS/KPConv"<KPConv@noreply.github.com&gt;; 
抄送: "或许"<1922797937@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HuguesTHOMAS/KPConv] about online test on semanti3d (#106)






这意味着我把云重命名为XXXX铺到X.txt.但是，在减为8的情况下，不使用这行代码，则ascii文件的名称由dataset.ascii_files在这里：

https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/datasets/Semantic3D.py#L148-L149

—
你收到这个是因为你评论了。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by Dawn-LLL** [comment]
老师，您好：
&nbsp; &nbsp; &nbsp; &nbsp;我前几天投稿你们的期刊，我的用户名和密码一直输入错误，目前没有办法查看稿件的情况。
&nbsp;通过邮箱找回，填写的邮箱没有错误，但是一直是失败的状态。&nbsp; &nbsp;

我是一作，姓名于丽丽 在读研究生 就读河南理工大学&nbsp; 我的导师于海洋老师&nbsp; &nbsp;&nbsp;
&nbsp;想请老师帮我找回密码和用户名，查看稿件的状态。&nbsp;
麻烦老师了&nbsp; 谢谢
