### ISSUE TITLE
Can you show us the file directory and format in the semantic3D zip package that you need to upload for online testing?

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#109]
Can you show us the file directory and format in the semantic3D zip package that you need to upload for online testing?I can't read the instructions on the official website clearly

**Comment by HuguesTHOMAS** [comment]
This is really simple. For reduced-8 challenge you need 4 txt files:

marketsquarefeldkirch4-reduced.labels 
stgallencathedral6-reduced.labels 
sg27_10-reduced.labels 
sg28_2-reduced.labels 

just select the 4 files together, right click, and compress in a zip format.

**Comment by longmalongma** [comment]
> This is really simple. For reduced-8 challenge you need 4 txt files:
> 
> marketsquarefeldkirch4-reduced.labels
> stgallencathedral6-reduced.labels
> sg27_10-reduced.labels
> sg28_2-reduced.labels
> 
> just select the 4 files together, right click, and compress in a zip format.

Thanks!
