### ISSUE TITLE
Voting scheme?

### ISSUE THREAD

**Issue by sshan-zhao** [HuguesTHOMAS/KPConv#110]
Hi,
Thank you for sharing the code of the great work on point cloud analysis.
I have a question about the evaluation. Do you apply the voting scheme on all experiments, e.g., ModelNet40, ShapePartNet, and S3DIS?
Thanks!

**Comment by HuguesTHOMAS** [comment]
Hi @sshan-zhao, 

Thx for your interest, yes I do apply the voting scheme for all my experiments. For ModelNet 40 it is a per-object vote and for the others, it is a per-point vote.

Best,
Hugues

**Comment by sshan-zhao** [comment]
> Hi @sshan-zhao,
> 
> Thx for your interest, yes I do apply the voting scheme for all my experiments. For ModelNet 40 it is a per-object vote and for the others, it is a per-point vote.
> 
> Best,
> Hugues

Thank you so much for your help!
I have another question: On ModelNet40 dataset, do you use 6800 points (average, per object) for training and inference? In comparison, most of the existing methods use 1000 points.
