### ISSUE TITLE
Semantic3D Dataset Error (visualizing)

### ISSUE THREAD

**Issue by RaIAustria** [HuguesTHOMAS/KPConv#111]
First of all congrats to one of the greatest open source codes existing for semantic segmentation!

I've faced some issues when I tried to visualize my trained and tested Semantic3D dataset. When I was executing the visualize_features.py file, I've got an value error in line 184 in visualize.py <Unsupported Dataset>. How can I fix it?

Thank you in advance!

**Comment by HuguesTHOMAS** [comment]
Thx for the compliment, and for your interest in my code. 

The visualization code is an experimental feature that is not supposed to be easily usable for any dataset like the training and test scripts. The script works for Scannet and S3DIS dataset though, which means it should be really easy for you to do some modifications to make it work on Semantic3D.

First, just before line 184, you should reproduce the line that handles S3DIS and Scannet datasets:

> elif model.config.dataset.startswith('Semantic3D'):
        label_op = model.inputs['point_labels']

then, you should follow the execution of the code and if you encounter another error, just try to reproduce what was coded for these two datasets but adapt it for Semantic3D.

Good luck with your project,
Hugues

**Comment by RaIAustria** [comment]
Thank you for the fast support!

I've already implemented the code you suggested last week. The execution of the code doesn't lead to an error at least, but unfortunately the visualization data (visu\top_activations\Relu00\) of Semantic3D are identical with the visualization data of S3DIS (so this dataset is gonna be visualized). I cannot figure out where I have to change the code to create the visualization data of the Semantic3D dataset.

I would appreciate another hint to get this fixed.

Thanks,
Ben

**Comment by HuguesTHOMAS** [comment]
Hi Ben, 

just look at the first line that is executed:

https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/visualize_features.py#L204-L221

You have to choose the path of a model trained on Semantic3D.

Best,
Hugues
