### ISSUE TITLE
Can’t report the results in your paper on S3DIS

### ISSUE THREAD

**Issue by lixincheng4026** [HuguesTHOMAS/KPConv#113]
Thanks for your brilliant work. I have training the network for S3DIS. But when I test the model, I can not report your result. Can you   provide your weight on S3DIS, so I can test the model. Thanks in advance.

**Comment by HuguesTHOMAS** [comment]
Hi @lixincheng4026,

There is a pretrained models link in the readme.

Best,
Hugues

**Comment by sshan-zhao** [comment]
> Hi @lixincheng4026,
> 
> There is a pretrained models link in the readme.
> 
> Best,
> Hugues

Hi, can you tell me how many points there exists in each point cloud on S3DIS dataset during training and inference? Thanks!

**Comment by HuguesTHOMAS** [comment]
Hi @sshan-zhao , 

I have no idea. You probably could find such information on the dataset website, or just by downloading it to see.

Best,
Hugues

**Comment by sshan-zhao** [comment]
Thank you for your reply. So, you use all points of a room as the input, right?
2020年10月7日 +1100 PM11:57 Hugues THOMAS <notifications@github.com>，写道：

**Comment by HuguesTHOMAS** [comment]
> Thank you for your reply. So, you use all points of a room as the input, right?

No I use input spheres and not rooms as input. It is all explained in the paper.
