### ISSUE TITLE
Pretrained deformable KPConv model?

### ISSUE THREAD

**Issue by beihaifusang** [HuguesTHOMAS/KPConv#114]
Hi Hugues, 

Thanks for your great work and open-source code. 

Currently, I'm trying to reproduce your results on S3DIS, but I found that only the rigid KPConv is provided with the pretrained model. Could you also provide the pre-trained model of deformable KPConv on S3DIS?

Best regards.

**Comment by HuguesTHOMAS** [comment]
Hi @beihaifusang,

I am sorry but I can't, it has been a long time since I did not use this code and I didn't keep the pretrained models.

Best,
Hugues

**Comment by beihaifusang** [comment]
Hi Hugues, 

Thanks for the quick response. Yet, if possible, could you instead provide the setting used for deformable KPConv on S3DIS? (as KPConv is the SOTA on S3DIS I think)

Best regards.

**Comment by HuguesTHOMAS** [comment]
I think they were the same as the rigid version for all parameters except the architecture which is the one used in NPM3D experiment: 
https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/training_NPM3D.py#L76-L93
