### ISSUE TITLE
About config.network_model

### ISSUE THREAD

**Issue by Inventor0** [HuguesTHOMAS/KPConv#115]
Thank you for your excellent work.  I want ask what does ‘config.network_model’ mean？ and what is 'segmentation'，'multi_segmentation'，'cloud_segmentation'，'multi_cloud_segmentation' mean respectively？

**Comment by HuguesTHOMAS** [comment]
Hi @Inventor0,

This parameter should be named `network_task` to be more precise. I ne the implementation, there are some times where we nee to choose different path corresponding to different task. For example when you create the network architecture, which will be different if it has to perform classification or segmentation. 

`segmentation` means "object part segmentation" like in ShapeNetPart.
`cloud_segmentation` means "scene semantic segmentation" like in S3DIS or Semantic3D
and the other two you can ignore as they are only experimental features that I tried but did not finished
