### ISSUE TITLE
can not preprocess s3dis data

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#121]
Hi, when I want to preprocess s3dis data, i meet this problem, can you help me?
Cloud Area_5 - Room 32/68 : /media/longma/demo/RandLA-Net-masterorigin/data/S3DIS/Stanford3dDataset_v1.2/Area_5/office_2
Cloud Area_5 - Room 33/68 : /media/longma/demo/RandLA-Net-masterorigin/data/S3DIS/Stanford3dDataset_v1.2/Area_5/office_20
Traceback (most recent call last):
  File "training_S3DIS.py", line 202, in <module>
    dataset = S3DISDataset(config.input_threads)
  File "/media/longma/demo/KPConv-master/datasets/S3DIS.py", line 152, in __init__
    self.prepare_S3DIS_ply()
  File "/media/longma/demo/KPConv-master/datasets/S3DIS.py", line 206, in prepare_S3DIS_ply
    cloud_points = np.vstack((cloud_points, object_data[:, 0:3].astype(np.float32)))
IndexError: too many indices for array

**Comment by longmalongma** [comment]
Is anything is wrong in Area_5 office_20 of s3dis dataset?

**Comment by HuguesTHOMAS** [comment]
I remember having some problem with one of the S3DIS txt file. The error message was not the same, but maybe it is something similar. Check this issue #82 

Otherwise your data might be corrupted in another way, try to download the files again.

Best,
Hugues

**Comment by longmalongma** [comment]
> Is anything is wrong in Area_5 office_20 of s3dis dataset?



> I remember having some problem with one of the S3DIS txt file. The error message was not the same, but maybe it is something similar. Check this issue #82
> 
> Otherwise your data might be corrupted in another way, try to download the files again.
> 
> Best,
> Hugues

Sorrry, I have downloaded s3dis again, ｂut the problem still arises.
