### ISSUE TITLE
npm3d result 

### ISSUE THREAD

**Issue by antonyvan** [HuguesTHOMAS/KPConv#122]
Hi, Hugues,
I noticed that your npm3d benchmark result is much higher than that shown in your kpconv paper 
https://npm3d.fr/paris-lille-3d

Is the result from the paper :  Semantic Classification of 3D Point Clouds with Multiscale Spherical Neighborhoods , which is shown in the webpage  or from your original kpconv paper? 

If these results are obtained from kpconv network, could you provide your modifications for training NPM3D in order to get your  benchmark result ? 

Thanks a lot.
Best regards

**Comment by HuguesTHOMAS** [comment]
Hi @antonyvan,

My best result on NPM3D was obtained with KPConv. Actually, I got the results a little later after the submission and that is why it is not in the paper. Unfortunately, this was a long time ago so I don't have the parameters that I used at the time. I can tell you that it was probably using the deformable version. If you want to reproduce it, you can try to reduce the input radius along with the first_subsampling_dl.
