### ISSUE TITLE
Question about shapeNet part classification network

### ISSUE THREAD

**Issue by cuevhv** [HuguesTHOMAS/KPConv#123]
Hi, I've read your paper and your work is really good. I have some doubts about it regarding shapeNet classification when training with all the objects.

- Does your input contain some one-hot encoding pointing out to which class it belongs? or only receives the neighboors and xyz points?
- What is the output dimension? is it 6? (parts motocycle has)

Thanks for your help :)

**Comment by HuguesTHOMAS** [comment]
Hi @cuevhv,

Thank you for your interest. These are good questions. First, the input does not have an encoding indicating its class, so in the first network layer, the features are computed in the same way for every object. However, in the network head, we use a multi-task learning scheme. For every shape, the network predicts the part segmentation of every possible class. So it returns a matrix of size [N, 16, 6]. During training, we ignore the 15 other object classes and apply the loss only to the concerned predictions. Same during tests, we only use the predictions from the concerned class.

Concerning the number of parts, there are 6 values for every shape, but we simply ignore the additional values when an object has less than 6 parts.

**Comment by cuevhv** [comment]
Thanks for the answer. What is the value of N at training time?

**Comment by HuguesTHOMAS** [comment]
N is the number of points in the batch and is variable, as explained in the paper and some issues already.
