### ISSUE TITLE
Can you provider your codes about cpp_wrappers based on tf2 and cuda11.0?

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#124]
Can you provider your codes about cpp_wrappers based on tf2 and cuda11.0? I can compile it when I using tf2 and cuda11.0. Looking forward to your reply.

**Comment by longmalongma** [comment]
> Can you provider your codes about cpp_wrappers based on tf2 and cuda11.0? I can compile it when I using tf2 and cuda11.0. Looking forward to your reply.
I using 3090,this is a problem, I 
  File "/home/lab601/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Op kernel context needs to provide a rendezvous.
	 [[{{node args_0/_1}}]]
	 [[IteratorGetNext]]
	 [[gradients/layer5/edge_conv1/BiasAdd_grad/BiasAddGrad/_1037]]
  (1) Internal: Op kernel context needs to provide a rendezvous.
	 [[{{node args_0/_1}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.


I guess the problem is that your package cpp_wrappers  is compiled incorrectly. Can you provide a package that can be compiled with tf2?

**Comment by HuguesTHOMAS** [comment]
Hi @longmalongma,

Sorry I am not working on this repo anymore so I can't provide new stuff. If you want to compile this in tf2, you will need to figure out the changes by yourself. Sorry that I cant be of any help here, and good luck with your problem.

Best,
Hugues

**Comment by longmalongma** [comment]
> Hi @longmalongma,
> 
> Sorry I am not working on this repo anymore so I can't provide new stuff. If you want to compile this in tf2, you will need to figure out the changes by yourself. Sorry that I cant be of any help here, and good luck with your problem.
> 
> Best,
> Hugues

Can you give me a concrete idea of how to solve this problem? I can hardly finish it by myself.
