### ISSUE TITLE
KPConv on SemanticKITTI

### ISSUE THREAD

**Issue by honggudrnjs** [HuguesTHOMAS/KPConv#130]
According to the leaderboard on SemanticKITTI competition, KPConv shows worse performance compared to other volumetric methods. Is there any reason on this phenomenon? By the way, thanks for sharing your code :)

**Comment by HuguesTHOMAS** [comment]
Hi @honggudrnjs,

The main reason is that I did the test on SemanticKitti at the end of my Ph.D. and I did not have much time to adapt the method to this particular data. I moved on to a new project since then and never improved the method
