### ISSUE TITLE
Use of Object Labels in Multi-Segmentation Head

### ISSUE THREAD

**Issue by maptastic** [HuguesTHOMAS/KPConv#133]
Can you explain whats happening when you use the object_labels for pooling in the multi-segmentation head (network_blocks.py)? Does this mean it is not possible to evaluate without having the labels?
Thanks

**Comment by HuguesTHOMAS** [comment]
Hi @maptastic,

your understanding is correct, I use the groundtruth object label to route the features to the dedicated network head. Most of the works on ShapeNetPart dataset consider each object label independently and train a specific network for the segmentation of each object class. A few others (including mine) use the same network for all the objects, but we still consider that we know the object labels.

> Does this mean it is not possible to evaluate without having the labels?

It is not what I do, but it is possible if your goal is an application where the object is not known in advance. Actually, it should not be very difficult to implement. You would need to add a global pooling and classification head after the last subsampling layer and add the classification loss during training. For the segmentation part, you can still use the grountruth object label when you train, but when you test, you can use the predicted object label instead.

Best,
Hugues

**Comment by maptastic** [comment]
Great! Thanks so much, this was very helpful!
