### ISSUE TITLE
Scannet dataset

### ISSUE THREAD

**Issue by Yakamoko** [HuguesTHOMAS/KPConv#136]
Hello Hugues,

Thanks in advance for your great work and contribution.

I am currently trying to feed some scanned pointclouds as input to the segmentation network, in order to remove the background noise and possibly extract only the object's pointcloud.  I have some indoor office scans that i took personally.

Working on your scene completion module, I was wondering if you have a link for the Scannet dataset that you train and use.

Greetings from Greece,
Yakamoko

**Comment by HuguesTHOMAS** [comment]
The scannet dataset can be found here:
http://www.scan-net.org/


Best,
Hugues
