### ISSUE TITLE
ScanNet training structure (rigid vs. deform).

### ISSUE THREAD

**Issue by ZhengdiYu** [HuguesTHOMAS/KPConv#139]
Hey,

Thank you for your work. 

I saw you mentioned the KPConv.rigid's mIoU is a bit higher than the deform version. To get a rigid version of ScanNet training structure. Should I replace all the 'resnetb_deformable' and 'resnetb_deformable_strided' to normal ''resnetb' and 'resnetb_strided' for KPConv.rigid? Is this what you mean?

Best,

**Comment by HuguesTHOMAS** [comment]
Hi @ZhengdiYu,

Yes exactly. You can copy the architecture of S3DIS:
https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/training_S3DIS.py#L71-L89

Best,
Hugues

**Comment by ZhengdiYu** [comment]
@HuguesTHOMAS 

Thank you for your quick reply! Close this now.
