### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by fenglupeter** [HuguesTHOMAS/KPConv#14]
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[104051,256] and type float

I am using a 6GB memory GTX1060 laptop.

How much graphic memory should I use?

**Comment by lhyfst** [comment]
You can reduce the batch size to solve the problem.

**Comment by HuguesTHOMAS** [comment]
Hi @fenglupeter,

The parameters are set for a 11GB GPU, like the one used in the paper. Like @lhyfst said, the batch size is the first thing you can reduce if you have a smaller GPU. however, you should try to keep it above 3 or 4, to avoid any problem with our varying batch strategy.

If it is not enough, you can increase the parameter `first_subsampling_dl `or decrease the parameter `in_radius`. The actual ratio is `in_radius = 50 * first_subsampling_dl`. You can reduce to 40 without affecting the performances drastically.

Best,
Hugues

**Comment by KangchengLiu** [comment]
I wonder how to change batch size in your config.py setting for the training of S3DIS?

**Comment by HuguesTHOMAS** [comment]
You can change the value ''batch_num'' of the Config class.
Remember that this value is an average as the batch size vary depending on the number of points in each input pointcloud
