### ISSUE TITLE
Bug on Scannet.py

### ISSUE THREAD

**Issue by ZhengdiYu** [HuguesTHOMAS/KPConv#140]
Hey,

You seem to use a wrong aggregation file. 
https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/datasets/Scannet.py#L206-L233

However, in the ScanNet repo https://github.com/ScanNet/ScanNet, it says:
|-- <scanId>_vh_clean_2.ply
    Cleaned and decimated mesh for semantic annotations
|-- <scanId>.aggregation.json, <scanId>_vh_clean.aggregation.json
    Aggregated instance-level semantic annotations on lo-res, hi-res meshes, respectively
|-- <scanId>_vh_clean_2.0.010000.segs.json, <scanId>_vh_clean.segs.json
    Over-segmentation of lo-res, hi-res meshes, respectively (referenced by aggregated semantic annotations)

Please have a check!

Best

**Comment by HuguesTHOMAS** [comment]
You seem to be right but I have not used the Scannet dataset for a very long time now. I will make a correction and if there is any other problems, don't hesitate to post another issue.

Thanks for spotting this.

Best,
Hugues

**Comment by ZhengdiYu** [comment]
> You seem to be right but I have not used the Scannet dataset for a very long time now. I will make a correction and if there is any other problems, don't hesitate to post another issue.
> 
> Thanks for spotting this.
> 
> Best,
> Hugues

Thank you for your quick reply! By the way, Could I ask about reason about creating a rasterize_mesh (finer point clouds) with very number of points for ScanNet training ? Why don't we just use the raw point cloud for training?

Best,
Zhengdi
