### ISSUE TITLE
Tools of drawing neural network

### ISSUE THREAD

**Issue by VincentChen1996** [HuguesTHOMAS/KPConv#142]
Hi, can you tell me how to draw KP-FCNN part in figure 9 of paper like you did? Is there any tool needed?

Best,
Vincent.

**Comment by HuguesTHOMAS** [comment]
Hi, 

No particular tools, I used PowerPoint to create this visualization. The only things that were not done in PowerPoint are the point clouds. I did screenshots from Mayavi visualizations.

Best,
Hugues

**Comment by VincentChen1996** [comment]
Thank you for your reply, I'll try it.
