### ISSUE TITLE
Instance Segmentation

### ISSUE THREAD

**Issue by snakch** [HuguesTHOMAS/KPConv#147]
Forgive me if this is obviously covered in the README, but I wonder whether you've trained this on the task of instance segmentation.

So in other words, instead of using ShapeNet parts where all table legs have the same label, you might want each individual part to be separated from the others.

More specifically, do you have results relating to that, or intuition on whether using the same procedure for Object Segmentation you describe would generalise well to this task?

Thanks!

**Comment by HuguesTHOMAS** [comment]
Hi @snakch,

No, I have not trained a KPConv network on an instance segmentation task (neither on a panoptic segmentation task btw). The network architecture is very similar to an image network, so it is definitely possible to adapt my segmentation architecture to detect instances by imitating instance segmentation strategies in other works like mask R-CNN. However, it would require a lot of coding, as implementing a deep point cloud network is not as easy as implementing image networks. 

You can also have a look at other works that perform instance segmentation on point clouds and replicate their idea with KPConv architecture. I think of Deep Hough Voting or Occuseg for example. Have a look at the 3D Semantic instance benchmark on [the scannet benchmark](http://kaldir.vc.in.tum.de/scannet_benchmark/) for a good overview on the state of the art methods.

Best,
Hugues

**Comment by snakch** [comment]
Thank you this makes sense!

Incidentally, while reading this paper https://arxiv.org/pdf/2010.15157.pdf I noticed that they compare their panoptic seg results to a combo of KPConv and either RangeNet ++ or PointPillars, meaning there exists such implementations out there. As far as I could find, they're not open-sourced but oh-well.

Anyway, thanks!
