### ISSUE TITLE
About 6-fold CV

### ISSUE THREAD

**Issue by yzheng97** [HuguesTHOMAS/KPConv#150]
Thanks for your work. I wonder the implementation of the 6-fold CV in your work. There are 2 implementations in current works: 
1. Compute 6 mIoUs for each fold, then sum and divide them by 6. 
2. Traverse segmentation results in all 6 areas and compute mIoU. 
I guess your work followed the first implementation. Am I right ?

**Comment by HuguesTHOMAS** [comment]
Hi @yzheng97,

You are right, and this is something that I thought of when doing the 6-fold CV too. In the end, I chose the first implementation if I remember correctly, as, at the time, it seemed like what was most commonly done.

Best,
Hugues

**Comment by yzheng97** [comment]
Many thanks!
