### ISSUE TITLE
Designing a cylindrical neighborhood.

### ISSUE THREAD

**Issue by ARITRA2296** [HuguesTHOMAS/KPConv#156]
In the Kernel function definition, the neighborhood is defined by a radius r and the domain of the definition is a sphere. Is it possible to change this shape to a cylinder?
If yes how can it be done?

**Comment by HuguesTHOMAS** [comment]
Hi @ARITRA2296,

Yes, everything is possible, you just need to find the way to implement it. Therefore the question is more: how difficult it would be, and how good are you at python :)

First of all, I would say you will have a much easier time coding this in the more recent [PyTorch implementation](https://github.com/HuguesTHOMAS/KPConv-PyTorch) of KPConv.

If you are ok with it, could you open an issue on the PyTorch GitHub and I will try to give you directions for this implementation?  Just so you know before you get into this, it could be quite hard to implement, there might be some tricks that we could find to make it simpler, but overall you will have to be quite good at python and even C++ for the neighborhoods

**Comment by ARITRA2296** [comment]
Hi @HuguesTHOMAS 
Thank you so much for reverting back. 
I shall open this issue in the PyTorch implementation. If can guide me on how and where to change the code that would be really great!
