### ISSUE TITLE
visualize in SemanticKITTI dataset

### ISSUE THREAD

**Issue by wanjunkim** [HuguesTHOMAS/KPConv#165]
Hi thank you for your effort! I have trained my model  using SemanticKITTI dataset.  Then, I want to visualize my model which is predicted. But your visualize.py can visualize only ModelNet and S3DIS... Is there any way to visualize the SemanticKitti model?

**Comment by wanjunkim** [comment]
oh sorry... I will write in pytorch model again

**Comment by magical1998** [comment]
Hello, can you share your pytorch visualization model for semantickitti?

**Comment by magical1998** [comment]
> oh sorry... I will write in pytorch model again

Hello, can you share your pytorch visualization model for semantickitti?
