### ISSUE TITLE
Problem with Compile the C++ extension modules

### ISSUE THREAD

**Issue by WesamOM** [HuguesTHOMAS/KPConv#166]
When running the command  "sh compile_wrappers.sh" on WSL I keep getting this error.
<img width="950" alt="Capture" src="https://github.com/HuguesTHOMAS/KPConv/assets/85706097/e7f82b73-bd45-4eb2-8874-c7802a8f6858">
<img width="158" alt="Capture1" src="https://github.com/HuguesTHOMAS/KPConv/assets/85706097/a479a902-be1f-4141-b69a-3edf097d8e38">
How do I solve this issue?

**Comment by WesamOM** [comment]
Now it gives me this error when running python3 train_S3DIS.py 
<img width="494" alt="Capture" src="https://github.com/HuguesTHOMAS/KPConv/assets/85706097/2954d735-b64d-4ff5-9567-11c2c1984795">

**Comment by LinLin1031** [comment]
@WesamOM  
Hello! I have encountered this problem as well, can you please tell me how you solved it?
