### ISSUE TITLE
release of trained model

### ISSUE THREAD

**Issue by amiltonwong** [HuguesTHOMAS/KPConv#18]
Hi, @HuguesTHOMAS ,

Would you also release the trained model?
I want to some further experiment on semantic segmentation on S3DIS dataset. Would you release the trained model for S3DIS dataset first?

thx!

**Comment by Sajjadmanal** [comment]
@HuguesTHOMAS Also, will you release this for Windows too (sometime in future) ?

**Comment by HuguesTHOMAS** [comment]
@amiltonwong, I will add trained models to the github in the next days.
@Sajjadmanal , our code cannot be released to windows as we use custom tf ops and their compilation is extremely complex for Windows.

**Comment by Sajjadmanal** [comment]
@HuguesTHOMAS Thanks for replying back. Also, will you release the model for npm3d too?

**Comment by HuguesTHOMAS** [comment]
@Sajjadmanal, yes.

**Comment by HuguesTHOMAS** [comment]
Hi guys,

I added pretrained models to the repo. An a new guide explaining how to load them. Do not hesitate to open a new issue if anything is wrong with them. 

Visualization scripts will follow soon.

Best,
Hugues
