### ISSUE TITLE
question about the visualization code

### ISSUE THREAD

**Issue by amiltonwong** [HuguesTHOMAS/KPConv#19]
Hi, @HuguesTHOMAS ,

I had tested the three visualization code; visualize_ERFs.py, visualize_deformations.py, visualize_features.py. But all of they return the following error:
```
Segmentation fault (core dumped)
```
Any hints to fix this issue? Or any other config should I modify?

thx!

**Comment by HuguesTHOMAS** [comment]
Hi @amiltonwong,

Visualization codes are not working right now. I will correct them and create a guides for visualization when I have some time.

Best,
Hugues

**Comment by amiltonwong** [comment]
@HuguesTHOMAS , thanks a lot :)

**Comment by amiltonwong** [comment]
Hi, @HuguesTHOMAS ,

Any update on progress about the visualization code?
