### ISSUE TITLE
gpu memory cost && missing kernels.convolution_ops 

### ISSUE THREAD

**Issue by andyzysraul** [HuguesTHOMAS/KPConv#2]
Hi, Thomas.  Thanks for your code sharing.  I have two questions hoping for your suggestions:
1. Gpu memory cost:  to train S3DIS datasets segmentation, for 3247 query points, 40 neighbors, 256 input channels,256 output channels, the theoretical gpu memory should be 3247x40x256x256x4(for float32)=32GB, which exceeds the 11GB capacity of 2080Ti. Is there some tricks to reduce the memory cost?
2. network_blocks.py imports kernels.convolution_ops, which is absent in current repository. Is this file still under modifying or will not be public?

**Comment by HuguesTHOMAS** [comment]
Hi, thanks for your interest in my work. The file "convolution_ops" was still under some late modifications as I detected a bug a few days ago. I uploaded it now so you should be able to run the code. 

As for your question on GPU memory, it can now be answered by looking at this file and the computations that effectively happen in KPConv. Every operation is commented with the dimensions of its output tensor for a clear understanding. You will see that we never need to handle a 3247x40x256x256 variable.
