### ISSUE TITLE
Add instructions for compiling with Ubuntu 18.04 -- Anaconda

### ISSUE THREAD

**Issue by noahtren** [HuguesTHOMAS/KPConv#20]
Thanks for sharing, this is really impressive work.

I got this running on Ubuntu 18.04 and can share my steps for getting it to work. Maybe you'd like to include these steps in INSTALL.md.
1. Remove the `-D_GLIBCXX_USE_CXX11_ABI=0` flag for each line in `tf_custom_ops/compile_op.sh`. I think this problem is from Ubuntu 18.04 having a new version of gcc.
2. Also, the specific version of cuDNN you mentioned (cuDNN 7.4) wasn't available on Anaconda, so I found that 7.3.1 works fine with CUDA 9.0 and TF.12. The problem seems to be in 7.5 and 7.6 (and potentially future versions too).

**Comment by HuguesTHOMAS** [comment]
Hello @noahtren,

Thanks a lot for your help. I will add these steps to `INSTALL.md`.
