### ISSUE TITLE
Cannot reproduce reported results on S3DIS Area5

### ISSUE THREAD

**Issue by Ghostish** [HuguesTHOMAS/KPConv#21]
Hi @HuguesTHOMAS，thanks for releasing the codes. We followed the default configurations and ran the code under `TensorFlow 1.11, Cuda9, cudnn7.3`. But we found the final results on S3DIS Area5 was just 60.24(much lower than the reported result 65.4)
![image](https://user-images.githubusercontent.com/7406087/64402595-1b24f200-d0a8-11e9-919f-1dfc1ac54507.png)

I wonder whether we've missed some details during the training. Or does it relate to the version of `TensorFlow`?

**Comment by HuguesTHOMAS** [comment]
Hi @Ghostish,

The results you obtained are quite strange. Have you run the `plot_convergence` script on your training log folder? What validation scores do you obtain? 

Also which snapshot did you to test? We found that our network can overfit and using the third our fourth snapshot (from epoch 150/200) gives better results than using the last snapshot. The line where you can choose the snapshot is:
https://github.com/HuguesTHOMAS/KPConv/blob/5f9cecae72c7a22cc4247b7852eee707ecab8fcd/test_any_model.py#L232 

try with `chosen_snapshot = 2` for example.
