### ISSUE TITLE
ubuntu16.0+cuda8.0+cudnn6.0 training ModelNet40

### ISSUE THREAD

**Issue by Ailce8862** [HuguesTHOMAS/KPConv#24]
Traceback (most recent call last):
  File "training_ModelNet40.py", line 213, in <module>
    model = KernelPointCNN(dataset.flat_inputs, config)
  File "/home/liangpan/KPConv/models/KPCNN_model.py", line 103, in __init__
    self.dropout_prob)
  File "/home/liangpan/KPConv/models/network_blocks.py", line 1065, in assemble_CNN_blocks
    training)
  File "/home/liangpan/KPConv/models/network_blocks.py", line 414, in resnetb_deformable_block
    config)
  File "/home/liangpan/KPConv/models/network_blocks.py", line 122, in KPConv_deformable
    modulated=config.modulated)
  File "/home/liangpan/KPConv/kernels/convolution_ops.py", line 370, in KPConv_deformable
    aggregation_mode)
  File "/home/liangpan/KPConv/kernels/convolution_ops.py", line 438, in KPConv_deform_ops
    new_neighbors_indices = tf.batch_gather(neighbors_indices, new_neighb_inds)
AttributeError: module 'tensorflow' has no attribute 'batch_gather'

**Comment by HuguesTHOMAS** [comment]
Hello @Ailce8862 

What version of Tensoflow are you using?

The op `tf.batch_gather` is [now deprecated](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/batch_gather). So you have two solutions:
1) Use an older version of tensorflow (1.12)
2) Replace `tf.batch_gather` with `tf.gather` and use the **_batch_dims_** argument.

Best,
Hugues

**Comment by Ailce8862** [comment]
my tensorflow version is 1.4 ubuntu16.0+cuda8.0+cudnn6.0 running on conda. If I want to choose the second method, how to modify the program.


| |
梁攀
|
|
邮箱：liangxiaopan8862@126.com
|

签名由 网易邮箱大师 定制

On 10/01/2019 19:17, Hugues THOMAS wrote:

Hello @Ailce8862

What version of Tensoflow are you using?

The op tf.batch_gather is now deprecated. So you have two solutions:

Use an older version of tensorflow (1.12)
Replace tf.batch_gather with tf.gather and use the batch_dims argument.

Best,
Hugues

**Comment by HuguesTHOMAS** [comment]
Hello @Ailce8862

Actually TF 1.4 is too old and does not include the function "batch_gather". You will not be able to run the code unless you upgrade your version.

Best,
Hugues

**Comment by Ailce8862** [comment]
thank you  for your help



| |
梁攀
|
|
邮箱：liangxiaopan8862@126.com
|

签名由 网易邮箱大师 定制

On 10/03/2019 22:37, Hugues THOMAS wrote:

Hello @Ailce8862

Actually TF 1.4 is too old and does not include the function "batch_gather". You will not be able to run the code unless you upgrade your version.

Best,
Hugues
