### ISSUE TITLE
NaN error during training

### ISSUE THREAD

**Issue by XuyangBai** [HuguesTHOMAS/KPConv#25]
Hi @HuguesTHOMAS Sorry for the bothering, have you ever met such kind of problem during training ?

<img width="1428" alt="屏幕快照 2019-10-03 下午10 05 06" src="https://user-images.githubusercontent.com/15166089/66134067-4a3c6e00-e62a-11e9-868f-9a5d51817a45.png">

My Configuration is:
```
CUDA Version 9.0.176, TF1.12,  GTX 1080
```

Like [Issue15](https://github.com/HuguesTHOMAS/KPConv/issues/15), this error also occurs randomly during training.

**Comment by HuguesTHOMAS** [comment]
Hi @XuyangBai ,

I will need a bit more details to understand what has happened here. What script did you run to get this error? Which parameter values?

Best,
Hugues

**Comment by XuyangBai** [comment]
Hi @HuguesTHOMAS  I use KPConv for my own dataset but I just use the config of ShapeNetPart as mine, except the first_subsampling_dl is set to 0.03 && I replace the deformable layer as the non-deformable ones.

And this error comes out randomly(even maybe after several epochs) during training. I have output the feature of the last layer, and it seems everything goes well before the error happens, there is no weird values appears.

**Comment by HuguesTHOMAS** [comment]
If you are using your own dataset, it will be hard for me to help you, as I wont be able to reproduce it. I can give you some piece of advice though.

First the error seems to come from a illegal memory access:
`indices[6] = -5002253071201698900`
There is no way the code returns such a value unless it has accessed an illegal memory address. So this could be caused by an indexing problem.

Something you need to know is that TF does not stop execution for a lot of errors when running on GPU. Instead, it continues with outlier values or NaNs as a result of the wrongful op. However, it will stop and raise an error when running on CPU. You can try to run you code on CPU simply by changing the line : 
https://github.com/HuguesTHOMAS/KPConv/blob/d60e5bf1326a183a6603b644ada1e183ab2150d8/utils/trainer.py#L83

I hope this helps. Good luck!
Hugues

**Comment by XuyangBai** [comment]
Thanks a lot @HuguesTHOMAS , your suggestion really helps. I run my code on CPU and found the wrongful ops.

Best,
Xuyang

**Comment by xbb2017** [comment]
> Thanks a lot @HuguesTHOMAS , your suggestion really helps. I run my code on CPU and found the wrongful ops.
> 
> Best,
> Xuyang

Hi Xuyang, could you please tell me where is the wrongful ops and how to solve it? I also met the same problems as you described before. Thank you so much.

**Comment by XuyangBai** [comment]
It is cased by dividing by zero. You should always add `1e-6` when use `tf.divide`, `tf.sqrt` etc.

**Comment by xbb2017** [comment]
> It is cased by dividing by zero. You should always add `1e-6` when use `tf.divide`, `tf.sqrt` etc.

Thank you so much!

**Comment by xbb2017** [comment]
> It is cased by dividing by zero. You should always add `1e-6` when use `tf.divide`, `tf.sqrt` etc.

Could you please share your revised 'convolution_ops.py' file with me? Thanks a lot!

**Comment by xbb2017** [comment]
> It is cased by dividing by zero. You should always add `1e-6` when use `tf.divide`, `tf.sqrt` etc.

Could you please share your revised 'convolution_ops.py' file with me? Thanks a lot!

**Comment by XuyangBai** [comment]
> > It is cased by dividing by zero. You should always add `1e-6` when use `tf.divide`, `tf.sqrt` etc.
> 
> Could you please share your revised 'convolution_ops.py' file with me? Thanks a lot!

Oh sorry It suddenly occurs to me that this error is happens for `tf.gather`.  On GPU if you use tf.gather with out of boundary index, it will not raise an error at once but stop at a random time(see my previous attach for the error message, the indices is a weird number) , but on CPU it  will raise the error immediately. That's why I find the bug using CPU version. Previously I have met some other errors related to dividing by zero. And I don't change `convolution_ops.py`, the bug comes from some code modified by myself.

**Comment by xbb2017** [comment]
> tf.gather

Thanks for information. So, have you already solved the problem about tf.gather on GPU?

**Comment by xbb2017** [comment]
> > > It is cased by dividing by zero. You should always add `1e-6` when use `tf.divide`, `tf.sqrt` etc.
> > 
> > 
> > Could you please share your revised 'convolution_ops.py' file with me? Thanks a lot!
> 
> Oh sorry It suddenly occurs to me that this error is happens for `tf.gather`. On GPU if you use tf.gather with out of boundary index, it will not raise an error at once but stop at a random time(see my previous attach for the error message, the indices is a weird number) , but on CPU it will raise the error immediately. That's why I find the bug using CPU version. Previously I have met some other errors related to dividing by zero. And I don't change `convolution_ops.py`, the bug comes from some code modified by myself.

I run successfully on ShapeNetPart dataset and Semantic3D dataset, but failed on NPM3D dataset. It got NaN after several steps during training.

**Comment by XuyangBai** [comment]
Yeah, it is a bug written by me. My `indices` looks for out of the range of `params `   😢

**Comment by xbb2017** [comment]
> Yeah, it is a bug written by me. My `indices` looks for out of the range of `params `

Ok, I will check my code.. Thank you so much!

**Comment by XuyangBai** [comment]
Do you check your GUDA and GPU version ?

**Comment by xbb2017** [comment]
> Do you check your GUDA and GPU version ?

My CUDA version is 10.2 and tensorflow is 1.12.3..

**Comment by HuguesTHOMAS** [comment]
Hi @xbb2017,

Maybe try to downgrade to CUDA 9.0. We previously found errors with CUDA 10 and RTX 2080 ti GPUs.

Best,
Hugues
