### ISSUE TITLE
Issues regarding newly-edited Scannet.py

### ISSUE THREAD

**Issue by hzykent** [HuguesTHOMAS/KPConv#26]
Hello,
Hope this post finds you well and thank you for your excellent work.
The newly-edited file Scannet.py seems to put these two lines from function "load_subsampled_clouds" to "__init__" by mistake.

        # List of training and test files
        self.train_files = np.sort([join(self.train_path, f) for f in listdir(self.train_path) if f[-4:] == '.ply'])
        self.test_files = np.sort([join(self.test_path, f) for f in listdir(self.test_path) if f[-4:] == '.ply'])

This will result in "No such file or directory" error since they are not created yet in the initialization stage.

> Dataset Preparation
> *******************
> Traceback (most recent call last):
>   File "training_Scannet.py", line 207, in <module>
>     dataset = ScannetDataset(config.input_threads, load_test=False)
>   File "/home/zeyu/Projects/KPConv/datasets/Scannet.py", line 149, in __init__
>     self.train_files = np.sort([join(self.train_path, f) for f in listdir(self.train_path) if f[-4:] == '.ply'])
> FileNotFoundError: [Errno 2] No such file or directory: 'Data/Scannet/training_points'
> (KPConv) zeyu@taigroup-System-Product-Name:~/Projects/KPConv$ python training_Scannet.py

Another issue is that when I start the training using the previous version of Scannet.py, the preprocessed data is weird. The ply files in the folder "training_meshes" could not be read by meshlab and the ply files in the folder "training_points" are extremely small(with sizes like 7kb). When I visualize the files in the folder "training_points", it seems like that they are all points along only one line. However, there seems to be no problems with the testing files.
![Screenshot from 2019-10-04 13-47-51](https://user-images.githubusercontent.com/43575254/66184164-cf1c9b80-e6ad-11e9-8967-1f24573dbda0.png)
![Screenshot from 2019-10-04 13-48-52](https://user-images.githubusercontent.com/43575254/66184167-d5ab1300-e6ad-11e9-8dd2-d7c0d2f68e1e.png)
Thank you in advance for your time and help.
Wish you good luck~(●'◡'●)

**Comment by HuguesTHOMAS** [comment]
Hi @hzykent,

Thanks a lot for you interest in this work. 

There was indeed a mistake in the newly-edited file Scannet.py. The method `prepare_pointcloud_ply` should be called between

        # Path of the training files
        self.train_path = join(self.path, 'training_points')
        self.test_path = join(self.path, 'test_points')

and

        # List of training and test files
        self.train_files = np.sort([join(self.train_path, f) for f in listdir(self.train_path) if f[-4:] == '.ply'])
        self.test_files = np.sort([join(self.test_path, f) for f in listdir(self.test_path) if f[-4:] == '.ply'])

Concerning the second issue, there was a typo in the method `prepare_pointcloud_ply`, the alignment matrix was converted in int32 instead of float32. For a rotation matrix which should be in [0,1], this was a problem.

The two mistakes have been corrected in the new version of the code. Everything should be fine now.

Best,
Hugues
