### ISSUE TITLE
Error in debug block 

### ISSUE THREAD

**Issue by OasisYang** [HuguesTHOMAS/KPConv#27]
Hello, I really appreciate your KPConv work and shared codes. However, I met a error when I run the `training_ModelNet50.py` in debug mode. In particular, I change this [line](https://github.com/HuguesTHOMAS/KPConv/blob/d60e5bf1326a183a6603b644ada1e183ab2150d8/training_ModelNet40.py#L247) to `trainer.train(model, dataset, debug_NaN=False)`. And I have the following error, could you help me to solve that? Thanks so much.
![image](https://user-images.githubusercontent.com/17880031/66424337-0ef7c180-e9d3-11e9-8dae-dc48521d96a6.png)

**Comment by HuguesTHOMAS** [comment]
Hi @OasisYang,

Thank you for you interest in KPConv. The "debug" mode is a very old part of my code which should have been removed. This functionality is not working anymore in my code.

If you need to debug something (NaN values appearing for example) you have two possibilities:

- Run the model on CPU like I explained [here](https://github.com/HuguesTHOMAS/KPConv/issues/25#issuecomment-537998854). 

- Use [tf.print](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/print) operation to track down the feature values during training.

I hope this is going to help you.

Best,
Hugues
