### ISSUE TITLE
Compile error: Could not convert const float to PointXYZ

### ISSUE THREAD

**Issue by nejcd** [HuguesTHOMAS/KPConv#3]
Thanks for sharing code. Nice work! 👍 

I have encountered a problem while compiling. I get following errors (here are just few):

error: could not convert 'P.PointXYZ::x' from **'const float'** to **'PointXYZ'**

`In file included from tf_neighbors/neighbors/neighbors.h:3:0,
                 from tf_neighbors/neighbors/neighbors.cpp:2:
tf_neighbors/neighbors/../../cpp_utils/cloud/cloud.h: In function 'PointXYZ floor(PointXYZ)':
tf_neighbors/neighbors/../../cpp_utils/cloud/cloud.h:142:26: error: could not convert 'P.PointXYZ::x' from 'const float' to 'PointXYZ'
  return PointXYZ(floor(P.x), floor(P.y), floor(P.z));
                        ~~^
tf_neighbors/neighbors/../../cpp_utils/cloud/cloud.h:142:38: error: could not convert 'P.PointXYZ::y' from 'const float' to 'PointXYZ'
  return PointXYZ(floor(P.x), floor(P.y), floor(P.z));
                                    ~~^
tf_neighbors/neighbors/../../cpp_utils/cloud/cloud.h:142:50: error: could not convert 'P.PointXYZ::z' from 'const float' to 'PointXYZ'
  return PointXYZ(floor(P.x), floor(P.y), floor(P.z));
                                                ~~^`

**OS**: Ubuntu 18.04.
I tried two versions of **g++ compilers**:

- g++-5     5.5.0 20171010
- g++         7.3.0

**Other**: 
python                    3.6.7
tensorflow-gpu     1.13.1

Any ideas or suggestions?

Thank you!

**Comment by HuguesTHOMAS** [comment]
It seems that the error comes from the definition of the "floor" function for the `PointXYZ` class. This function just calls the c++ function `floor(float x)` defined in "cmath" header. 

I added the line :
`#include <cmath> `
at the beginning of the file. Does it compile now?

**Comment by nejcd** [comment]
It does. 

I had also tried with `#include <math.h>` and it works as well. 

Thans.
