### ISSUE TITLE
Problems about running training_ShapeNetPart.py 

### ISSUE THREAD

**Issue by Violetit** [HuguesTHOMAS/KPConv#32]
Hi @HuguesTHOMAS 
When I run the `training_ShapeNetPart.py` script, the error below occurred many times, and the program stopped. 
And I have followed your `INSTALL.md` operations.

`Step 00009033 L_out=0.121 L_reg=0.080 L_p=0.282 Acc=0.96 ---  314.13 ms/batch (Averaged)
2019-10-22 11:18:28.785661: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-10-22 11:18:28.785715: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1
Aborted (core dumped)`

Can you help me to solve this problem?

**Comment by HuguesTHOMAS** [comment]
Hi @Violetit,

I don't think I have seen this error before. I will need more information.

What GPU are you using? 

What parameters did you use in your training?

A way to debug the error can be to run the network in CPU mode (see this [issue](https://github.com/HuguesTHOMAS/KPConv/issues/25#issuecomment-537998854)). You can try to do it and see if any error arise.

**Comment by Violetit** [comment]
> Hi @Violetit,
> 
> I don't think I have seen this error before. I will need more information.
> 
> What GPU are you using?
> 
> What parameters did you use in your training?
> 
> A way to debug the error can be to run the network in CPU mode (see this [issue](https://github.com/HuguesTHOMAS/KPConv/issues/25#issuecomment-537998854)). You can try to do it and see if any error arise.


I use the 2080ti, and I didn't change any parameters.

**Comment by HuguesTHOMAS** [comment]
have you tried to debug in CPU mode?

Which version of CUDA and Tensorflow are you using?

**Comment by Violetit** [comment]
> have you tried to debug in CPU mode?
> 
> Which version of CUDA and Tensorflow are you using?

CUDA 9.0 and tensorflow-gpu 1.12.0
But it also works correct sometimes.

**Comment by HuguesTHOMAS** [comment]
Okay, your version does not seem to be a problem then. An error that does not happen every time is really hard to track down. Personally, I do not have much time these days to dig into that problem, but I would be very interested if you find the origin of this error.

**Comment by Violetit** [comment]
> Okay, your version does not seem to be a problem then. An error that does not happen every time is really hard to track down. Personally, I do not have much time these days to dig into that problem, but I would be very interested if you find the origin of this error.

Many thanks ， wish you all the best ！
