### ISSUE TITLE
Could someone help provide a pytorch version?

### ISSUE THREAD

**Issue by zxczrx123** [HuguesTHOMAS/KPConv#35]
I want to migrate this to Windows,but I failed.So I want some one could help me.

**Comment by HuguesTHOMAS** [comment]
Hi @zxczrx123,

As I explained in another post. Our code cannot be used on windows right now as it invloves custom TF ops. I might create a TF 2.0 version of the code in the future, but it is not the priority right now.

A Pytorch version was already discussed [here](https://github.com/HuguesTHOMAS/KPConv/issues/12#issue-450595118). But I think it has not been completed.

Best,
Hugues
