### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by peterjohnsonhuang** [HuguesTHOMAS/KPConv#36]
Hi, thank for your contribution, but I met with this error tensorflow.python.framework.errors_impl.NotFoundError: tf_custom_ops/tf_neighbors.so: undefined symbol: _ZN10tensorflow12OpDefBuilder5InputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

I am using ubuntu 18.04 with anaconda3, cuda-toolkit=9.0, cudnn=7.3.1  tf-gpu=1.12.0
can you help me with that?
thanks

**Comment by yaping222** [comment]
Hi, Hugues, thank you very much for your great work.
I met the same issue：
tensorflow.python.framework.errors_impl.NotFoundError: tf_custom_ops/tf_neighbors.so: undefined 
symbol: _ZN10tensorflow12OpDefBuilder5InputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by HuguesTHOMAS** [comment]
Hi @peterjohnsonhuang and @yaping222,

Hopefully, [this answer](https://github.com/HuguesTHOMAS/KPConv/issues/9#issuecomment-494537319) may solve your problem.

Best,
Hugues

**Comment by peterjohnsonhuang** [comment]
Hi, @HuguesTHOMAS,
Thank you for the reply, I've tried the method you mentioned but got same error message. However, method in this issue [https://github.com/HuguesTHOMAS/KPConv/issues/38#issue-516872226](url) helped me solve it.

**Comment by yaping222** [comment]
Hi, @HuguesTHOMAS , thank you very much for your reply. I solved the issue by keeping D_GLIBCXX_USE_CXX11_ABI=0.
