### ISSUE TITLE
Scene Segmentation on ScanNet

### ISSUE THREAD

**Issue by dtczhl** [HuguesTHOMAS/KPConv#38]
Thank you for your repo. 

Could you please provide me with the script and the pre-trained model for scene segmentation on ScanNet?

BTW, about the instructions for Ubuntu 18.04. I don't have to remove `-D_GLIBCXX_USE_CXX11_ABI=0` flag. Instead, I need to make minor changes to `cpp_wrappers/cpp_utils/cloud/cloud.h` by 
1) add  `<cmath>` header
2) line 141
`return PointXYZ(floor(P.x), floor(P.y), floor(P.z));` 
to `return PointXYZ(std::floor(P.x), std::floor(P.y), std::floor(P.z));`

**Comment by HuguesTHOMAS** [comment]
Hi @dtczhl,

Thank you for your update on the instructions for Ubuntu 18.04. The script for semantic segmentation on Scannet is already there. I just did not add the instructions. It is very similar to the other datasets and you should be able to use it easily.

Concerning the pretrained model. I will try add it with the instructions in the next weeks. Although I am very busy right now.

Best,
Hugues

**Comment by dtczhl** [comment]
@HuguesTHOMAS  Thanks for your quick reply. 

Best,
Huanle
