### ISSUE TITLE
Cloud completion

### ISSUE THREAD

**Issue by no-materials** [HuguesTHOMAS/KPConv#39]
Thanks for the great implementation! The paper suggests that KPConv could be well suited for the task of partial point cloud completion. Have you experimented with this type of problem using the KPConv operator in a specific architecture?

**Comment by HuguesTHOMAS** [comment]
Hi @no-materials,

KPConv could indeed be well suited for the task of partial point cloud completion. You would have to adapt the decoder part of the network to add generation of points in parallel to the upsampling operations. I did not have a chance to work on such architecture yet though. If it works, it could definitely be the subject of a paper.

Best,
Hugues

**Comment by no-materials** [comment]
Many thanks!
