### ISSUE TITLE
Model store and reload.

### ISSUE THREAD

**Issue by XuyangBai** [HuguesTHOMAS/KPConv#41]
Hi @HuguesTHOMAS Sorry for the bothersome.

I wonder is it possible to reload the weight that trained in another `first_subsampling_dl` parameter ? (like I first trained the network using 3cm voxel and then want to use it in a larger scene with 5cm voxel size?).  Another question is when reload the pretrained weight, if I change `config.first_subsampling_dl`, will the location of kernel points change accordingly ? I tried it and found it will, but I cann't find the code doing such things, the model reload part is simply done by `self.saver.restore`.

Thanks a lot !

**Comment by HuguesTHOMAS** [comment]
Hi @XuyangBai,

This is a very sensitive point that I did not take into account when implementing my method. Ideally a trained network should be testable with a different `first_subsampling_dl`. But I think it is not the case in the current code.

To answer your question, the location of kernel points do not change accordingly to the new value of `first_subsampling_dl`. When you reload the weights of the network, you also reload the kernel point locations which are dependant of the old `first_subsampling_dl` parameter. It means that your new network will not work. It is the same for other parameters like the architecture or the `first_features_dim`. You cannot change their value when reloading the network.

I think there is a workaround in the case of `first_subsampling_dl` parameter. You need to load the old `first_subsampling_dl` value (with a simple `config.load`), and then after reloading all weights with `self.saver.restore`, you can rescale the kernel points to the new radius with something like 

            for v in restore_vars:
                if 'kernel_points' in v.name:
                    rescale_op = v.assign(tf.multiply(v, new_dl / old_dl))
                    self.sess.run(rescale_op)

**Comment by XuyangBai** [comment]
Hi @HuguesTHOMAS Yes, I tried your solution and found it works ! Thanks a lot.

**Comment by beihaifusang** [comment]
Hi, thanks for your great work and code, and sorry for continuing on this. @HuguesTHOMAS 

While I'm trying to speed up the training, I found the kernel points are also evaluated and saved into ply format. I'm a bit confused of the reason behind this bit of code.

I mean, the weights of kernel points are saved by the tensorflow together with weights in other layer into the checkpoint files, and the kernel point location are computed & saved in model construction, so why do we still save the kernel points into separate files?

As I'm using the rigid version for the moment, I'm guessing saving the kernel points is for the deformable version?

Best regards.

**Comment by HuguesTHOMAS** [comment]
You are right, it was just a debugging thing that I did for convenience to be able to look at them with CloudCompare. And it only applies for rigid KPConv, because the deformable version does not have only one deformation, it deforms differently for every convolution location, so you cannot save that in ply files.

**Comment by beihaifusang** [comment]
I see, thank you so much!
