### ISSUE TITLE
problem about ”sh compile_wrappers.sh ”

### ISSUE THREAD

**Issue by Codeczh** [HuguesTHOMAS/KPConv#45]
(kpconv) czh@dirac:~/project/KPConv/cpp_wrappers$ sh compile_wrappers.sh 
running build_ext
building 'grid_subsampling' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
C compiler: gcc -pthread -B /farm/czh/anaconda3/envs/kpconv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/cpp_wrappers
creating build/temp.linux-x86_64-3.6/cpp_wrappers/cpp_utils
creating build/temp.linux-x86_64-3.6/cpp_wrappers/cpp_utils/cloud
creating build/temp.linux-x86_64-3.6/grid_subsampling
compile options: '-I/farm/czh/anaconda3/envs/kpconv/lib/python3.6/site-packages/numpy/core/include -I/farm/czh/anaconda3/envs/kpconv/include/python3.6m -c'
extra options: '-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0'
gcc: ../cpp_utils/cloud/cloud.cpp
gcc: grid_subsampling/grid_subsampling.cpp
gcc: wrapper.cpp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /farm/czh/anaconda3/envs/kpconv/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                 from /farm/czh/anaconda3/envs/kpconv/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /farm/czh/anaconda3/envs/kpconv/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from wrapper.cpp:2:
/farm/czh/anaconda3/envs/kpconv/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
grid_subsampling/grid_subsampling.cpp: In function ‘void grid_subsampling(std::vector<PointXYZ>&, std::vector<PointXYZ>&, std::vector<float>&, std::vector<float>&, std::vector<int>&, std::vector<int>&, float, int)’:
grid_subsampling/grid_subsampling.cpp:99:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < ldim; i++)
                       ~~^~~~~~
wrapper.cpp: In function ‘PyObject* grid_subsampling_compute(PyObject*, PyObject*, PyObject*)’:
wrapper.cpp:70:98: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  static char *kwlist[] = {"points", "features", "classes", "sampleDl", "method", "verbose", NULL };
                                                                                                  ^
wrapper.cpp:70:98: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
wrapper.cpp:70:98: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
wrapper.cpp:70:98: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
wrapper.cpp:70:98: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
wrapper.cpp:70:98: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
g++ -pthread -shared -B /farm/czh/anaconda3/envs/kpconv/compiler_compat -L/farm/czh/anaconda3/envs/kpconv/lib -Wl,-rpath=/farm/czh/anaconda3/envs/kpconv/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpp_wrappers/cpp_utils/cloud/cloud.o build/temp.linux-x86_64-3.6/grid_subsampling/grid_subsampling.o build/temp.linux-x86_64-3.6/wrapper.o -o /farm/czh/project/KPConv/cpp_wrappers/cpp_subsampling/grid_subsampling.cpython-36m-x86_64-linux-gnu.so

**Comment by HuguesTHOMAS** [comment]
Hello @Codeczh,

If you only post a log without any explanation, I won't be able to help you. I don't even see an error in the log you printed, only warnings. 

Could you elaborate more on your problem?

**Comment by Codeczh** [comment]
@HuguesTHOMAS  Thank you for your reply. I just find the reason that my sever installed cuda10, not supported as the readme said.

**Comment by jspruitt** [comment]
I'm also having similar errors. I am using a conda enviorment with tensorflow 1.10.0(tried 1.12.0 and still had an error). I'm using ubuntu 18.04, but have switched to different gcc versions, so that's not the problem. I also have cuda 9.0 and cudnn 7.4.5 installed.

I fixed these errors:
ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
static char kwlist[] = {"points", "features", "classes", "sampleDl", "method", "verbose", NULL };

and

\comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int i = 0; i < ldim; i++)

but the compile_wrappers is still not compiling.

**Comment by jspruitt** [comment]
I fixed it. You set CC to where gcc is and CXX to where g++ is
