### ISSUE TITLE
the running error I encountered about running Semantic3D.py

### ISSUE THREAD

**Issue by changhexingchen** [HuguesTHOMAS/KPConv#46]
@HuguesTHOMAS Thanks for your  sharing the code！ I encountered this error :
“  AttributeError: module 'cpp_wrappers.cpp_subsampling.grid_subsampling' has no attribute 'compute'  ”
When I run the script Semantic3D.py. 
Could you give me some help? Thank you very much!

**Comment by HuguesTHOMAS** [comment]
Hello @changhexingchen,

have you compiled the cpp wrappers as instructed in `INSTALL.md`? Did you get any error message?

Best,
Hugues

**Comment by changhexingchen** [comment]
Firstly, thank you for your reply. Now the script "training_Semantic3D.py"  works.
I want to ask for your advice about this code： data = np.loadtxt(txt_file) in the script Sematic3D.py. when it reads the dataset, such as "sg27_station1_intensity_rgb.txt"， it will take very long time. One reason about that may lie in the size of the dataset file. eg, the size of the file "sg27_station1_intensity_rgb.txt"  is about 11GB. I do not know if there is a better solution？

**Comment by a462428** [comment]
I follow the install.md still encounter same problem QQ

**Comment by HuguesTHOMAS** [comment]
Well, you can open a new issue with more details if you want some help.

**Comment by GoPark1995** [comment]
Thanks for your sharing the code！
I funding error about "AttributeError: module 'cpp_wrappers.cpp_subsampling.grid_subsampling' has no attribute 'compute'. "
How  can I solve this problem
I used to sh compile_wrappers.sh  install the file.

**Comment by HuguesTHOMAS** [comment]
Follow all the compilation steps and if there is an error during compilation, please report it in a new issue.
