### ISSUE TITLE
How to visualize the result as Figure 4 in paper (for segmentation)?

### ISSUE THREAD

**Issue by vince2003** [HuguesTHOMAS/KPConv#48]
Dear @HuguesTHOMAS,
 Thank you very much for your source code. After training,  I  want to visualize the result as  Figure 4 for the S3DIS dataset. However, I can not do it. I only have the result from the visualization of layers.
 Please help me to visualize the final result for segmentation like figure 4?
 Thank you again!

**Comment by HuguesTHOMAS** [comment]
Hi @quangvinh242003,

The visualization is very easy. After training, you should have folders with the predictions on validation clouds. The prediction files are in _.ply_ format and located in `results/Log_YYYY-MM-DD_HH-MM-SS/val_preds_XXX/Area_5.ply`.

These files can be displayed using any point cloud visualization tool. I personally used CloudCompare, a free open source software.

You also get prediction files when you test your network, they are located in the `test` folder.

Best,
Hugues

**Comment by quangvinh242003** [comment]
Hi @HuguesTHOMAS,
Thank you for your reply. However, my prediction files are without semantic segmentation by different colors as the fig:
![Screenshot from 2019-12-06 22-55-48](https://user-images.githubusercontent.com/39032947/70331756-758a4600-1883-11ea-8f1e-d7aea9fbe0a0.png)

but the result that I want should be semantic segmentation by different colors like the following fig 4 in your paper:
![fig4](https://user-images.githubusercontent.com/39032947/70331986-f5181500-1883-11ea-873a-c5235ccc78ed.png)

**Comment by HuguesTHOMAS** [comment]
Do you know how to use CloudCompare? 

When you load a ply file, you have to change the last line of the loading window called "Scalar". Choose the "class" or "label" scalar values in the drop-down menu. 

If you want more info, just go to the [CloudCompare wiki](https://www.cloudcompare.org/doc/wiki/index.php?title=Main_Page#Getting_started).

**Comment by quangvinh242003** [comment]
I got it!
Thank you very much!
