### ISSUE TITLE
NAN problem

### ISSUE THREAD

**Issue by liuxinren456852** [HuguesTHOMAS/KPConv#5]
Have you tested KPConv only in tf 1.12?Which cuda version do you use? 
         I also had a NAN problem when training npm data. My environment is tf 1.8 (cuda 9.2). Can you give me some advice?

**Comment by HuguesTHOMAS** [comment]
The configuration we tested are listed in `INSTALL.md`. The version of tensorflow should not be a problem except for 1.13, as CUDA 10 seem to have problems with RTX 2080ti.

In your case, I think the problem come from your version of CUDA. Tensorflow 1.8 does not support CUDA 9.2, you should use CUDA 9.0 instead.

**Comment by liuxinren456852** [comment]
thank you for your reply. I installed tensorflow 1.8 (cuda 9.2) from the source code.😢

**Comment by liuxinren456852** [comment]
Thank you for your reply, I will try it.😊
