### ISSUE TITLE
Questions about deformable KPConv.

### ISSUE THREAD

**Issue by XuyangBai** [HuguesTHOMAS/KPConv#52]
Hi @HuguesTHOMAS 

I have some questions regards the deformable KPConv, in [convolution_ops.py](https://github.com/HuguesTHOMAS/KPConv/blob/935a2bd75775b07eda8cecbacf2d91b2dd7cbf8d/kernels/convolution_ops.py#L429). After getting the deformed Kernel points, what's the following code used for? Why we need to calculate a new neighbors indices ? (In my understanding the deformable convolution learns the offset for each kernel point to fit the geometry of point cloud, so why should the neighbor relationship of the points get changed?) 
```python
    # Boolean of the neighbors in range of a kernel point [n_points, n_neighbors]
    in_range = tf.cast(tf.reduce_any(tf.less(sq_distances, KP_extent**2), axis=2), tf.int32)

    # New value of max neighbors
    new_max_neighb = tf.reduce_max(tf.reduce_sum(in_range, axis=1))

    # For each row of neighbors, indices of the ones that are in range [n_points, new_max_neighb]
    new_neighb_bool, new_neighb_inds = tf.math.top_k(in_range, k=new_max_neighb)

    # Gather new neighbor indices [n_points, new_max_neighb]
    new_neighbors_indices = tf.batch_gather(neighbors_indices, new_neighb_inds)

    # Gather new distances to KP [n_points, new_max_neighb, n_kpoints]
    new_sq_distances = tf.batch_gather(sq_distances, new_neighb_inds)

    # New shadow neighbors have to point to the last shadow point
    new_neighbors_indices *= new_neighb_bool
    new_neighbors_indices += (1 - new_neighb_bool) * shadow_ind
```
Another question is about the `modulated`, I notice that for all the training script you set the `modulated` to False but you still implement the modulated case for deformable convolution. Could you please provide some explanation on what's the `modulated` means and how does it work?

Thanks a lot !

Best,
Xuyang

**Comment by HuguesTHOMAS** [comment]
Hi @XuyangBai,

To allow the deformable to reach further than normal convolution, we use a larger radius of convolution sphere. Therefore, there is a lot more neighbors to compute distance from. However, not all these neighbors will be in range of a deformed kernel point, so we eliminate the neighbors that are not in range of any kernel point before actually doing the big computations. It is not an ideal implementation but it helps a little bit, in term of speed and memory.

For the "modulated", it is something that you can see in the [second article of deformable convolution for images](https://arxiv.org/abs/1811.11168). It gives the ability to the network to learn "modulations" in addition to shifts. It means that the network can decide wich deformed kenrel points are the most important ones.

In practice, I did not see any difference in the performances so I did not use it, but I still implemented it, so it is there to test if someone wants to explore this possibility. 

Best,
Hugues

**Comment by XuyangBai** [comment]
Hi @HuguesTHOMAS 

Thanks for your reply! It makes sense to me .

Best,
Xuyang.
