### ISSUE TITLE
ModelNet40 Input rotation

### ISSUE THREAD

**Issue by jiahaowork** [HuguesTHOMAS/KPConv#54]
It seems that in the training script of ModelNet40 classification, the rotation augmentation is set to None. Does it mean that you report the results for ModelNet40 classification for the case that all the shapes are at the original canonical position (without any rotation around the y axis)?

Thank you!

**Comment by HuguesTHOMAS** [comment]
Hi @jiahaowork,

There are two version of ModelNet40. The original one and an aligned version. I only used the original dataset. So when the rotation augmentation is set to `None`, the shape are in their original orientation, which is not always a canonical alignment.

Best,
Hugues
