### ISSUE TITLE
Semantic3D.py regression

### ISSUE THREAD

**Issue by phil0stine** [HuguesTHOMAS/KPConv#57]
I made an inline [comment](https://github.com/HuguesTHOMAS/KPConv/commit/21ac8cb4e3b3ae8268c4bf1fecc301c116838a11#r36857116) that outlines the problem. It looks like moving the declaration of `self.train/test files` introduced a regression bug for a first time run. None of the `ply` files have been created yet, nor have the `DATA` subdirectories that the definitions depend on. The result for a new install is an error message about `ply_subsampled/train` not existing

**Comment by HuguesTHOMAS** [comment]
Hi @phil0stine,

You are right, thank you for your comment. I am so used to having all the dataset already preprocessed that I forget sometimes the preprocessing even exists. I will correct this mistake soon.

Best,
Hugues
