### ISSUE TITLE
Question about grid_subsampling code

### ISSUE THREAD

**Issue by hi-zhengcheng** [HuguesTHOMAS/KPConv#58]
Thanks for your great work and nice code. 

My question is about the code in grid_subsampling when computing the subsampled_class for the subsampled point. The code is: 

https://github.com/HuguesTHOMAS/KPConv/blob/935a2bd75775b07eda8cecbacf2d91b2dd7cbf8d/cpp_wrappers/cpp_subsampling/grid_subsampling/grid_subsampling.cpp#L100

The logic here is to find out the label with the most occurrence number. The label's occurrence  number is stored in an `unordered_map`, with different labels as different keys, and corresponding occurrence number as values. 

The code is using `max_element` to do it, **but does not pass the third `comp` param**. So what the code actually does, is just to find the max key in the `unordered_map`. It's not what we want.  

I think we need to add the third param to `max_element` like this:
```C
max_element(v.second.labels[i].begin(), v.second.labels[i].end(), 
    [](const pair<int, int>&a, const pair<int, int>&b){return a.second < b.second;})
```

My test code is as follows:
```C
#include <iostream>
#include <unordered_map>
#include <algorithm>

using namespace std;

int main() {
    unordered_map<int, int> map; // label -> occurrence number
    map[5] = 2;
    map[2] = 3;

    auto r1 = max_element(map.begin(), map.end());
    cout << r1->first << "->" << r1->second << endl; // output: 5->2, it's wrong!


    auto r2 = max_element(map.begin(), map.end(),
            [](const pair<int, int>&a, const pair<int, int>&b){return a.second < b.second;});
    cout << r2->first << "->" << r2->second << endl; // output: 2->3, it's right

    return 0;
}
```

**Comment by HuguesTHOMAS** [comment]
Hi @hi-zhengcheng,

Thank you very much for your comment, this is indeed a mistake from me. I wrote this piece of code a long time ago, even before creating KPConv. I made multiple changes through the years and did not always check the validity of the result. 

I will correct this mistake soon. Hopefully, it does not invalidate the result of the method, as we always evaluate on the original point clouds and not the subsampled ones. If this mistake had any effect, it would only have been lowering a little bit the results by altering the training groundtruth.

Best,
Hugues

**Comment by beihaifusang** [comment]
Hi, sorry for re-open this one. I'm a newbie in this field and has found this 'grid_subsampling' modules being used in several recent works. While I'm learning this code, I'm interested in its origin. It seems the code is originally written by you and is based on the PCL. Could you confirm this?

Thank you very much.

**Comment by beihaifusang** [comment]
Hi @HuguesTHOMAS , sorry for continuing on this one. I'm a newbie in this field and has found this 'grid_subsampling' modules being used in several recent works. While I'm learning this code, I'm interested in its origin. It seems the code is originally written by you and is based on the PCL. Could you confirm this?

Thank you very much.

**Comment by HuguesTHOMAS** [comment]
Hi @beihaifusang,

I was not aware this particular peace of code was used in other recent works. I would be curious to know which ones. 

As for its origin, it is just a simple implementation that I wrote myself, it's not based on PCL, I wrote this during my PhD.

**Comment by beihaifusang** [comment]
I see, probably the pointXYZ part let me think it's from PCL. Particularly, I encountered this piece of code in RandLA-Net (here: https://github.com/QingyongHu/RandLA-Net/tree/master/utils/cpp_wrappers)

**Comment by HuguesTHOMAS** [comment]
Thanks for the info
