### ISSUE TITLE
Where is modelnet40_train.txt and modelnet40_test.txt

### ISSUE THREAD

**Issue by lhyfst** [HuguesTHOMAS/KPConv#6]
Thanks for your work!

I am wondering where are modelnet40_train.txt and modelnet40_test.txt? I download ModelNet40.zip and unzip it, but I cannot find these two files.

![image](https://user-images.githubusercontent.com/29816816/57904453-a17ea500-7827-11e9-9170-f3fc3ea68a6b.png)

![image](https://user-images.githubusercontent.com/29816816/57904501-d559ca80-7827-11e9-9cd0-5ec64e6f3ec6.png)

**Comment by lhyfst** [comment]
My bad, I did not download the correct dataset.

**Comment by NanBlanc** [comment]
here is the link to the dataset to used from [TensorFlow KPConv ModelNet40 instruction page](https://github.com/HuguesTHOMAS/KPConv/blob/master/doc/object_classification_guide.md) : 
[RESAMPLED_MODELNET40](https://shapenet.cs.stanford.edu/media/modelnet40_normal_resampled.zip)
