### ISSUE TITLE
KP-CNN on XYZ without normals

### ISSUE THREAD

**Issue by neumicha** [HuguesTHOMAS/KPConv#62]
Hi,
I want to apply KP-CNN on some simple XYZ files to compare the results with other methods and on my own data.
I preprocessed my point clouds - for the moment there are 'training/cloud1.xyz', 'training/cloud2.xyz', 'testing/cloud1.xyz', and 'testing/cloud2.xyz'. Their format is now:

> X Y Z CLASS
> 10.567 3.2987 3.73 1

Unfortunately there is only one example for classification. It's on ModelNet40, which also includes normals. I now have trouble getting it to work without normals on this very usual format... Especially random_balanced_gen() and get_tf_mapping() are my problem.

Can you provide code for simple XYZ files?
I am also not quite sure what the `in_features_dim` parameter does.

Thanks

**Comment by HuguesTHOMAS** [comment]
Hi @neumicha,

For XYZ files, it is actually very simple, you just have to ignore everything that concerns normals. The code loads the training text files here:
https://github.com/HuguesTHOMAS/KPConv/blob/a54f594f613e3f8801f9946ec0f3e3d2ff5f994b/datasets/ModelNet40.py#L208
And the test text files here:
https://github.com/HuguesTHOMAS/KPConv/blob/a54f594f613e3f8801f9946ec0f3e3d2ff5f994b/datasets/ModelNet40.py#L265
If you do not want to change anything in the code, a simple solution would be to add fake normals to the `data` array, with something like 

        data = np.hstack((data[:, :3], data[:, :3]*0))

**Comment by HuguesTHOMAS** [comment]
Actually there is something strange, why do you have a column for class in your xyz file if it is a classification problem? Isn't the class the same for all points in cloud1.xyz?

**Comment by neumicha** [comment]
Hi @HuguesTHOMAS 

I think I misunderstood your definition of KP-CNN and KP-FCNN.

What I called a classification problem (big outdoor scenes with point-wise labels: house, car, pedestrian, ...) is the problem corresponding to your KP-FCNN, right?

I will have a look through your KP-FCNN examples to see what matches my data best.

Okay, using fake normals/colors is a solution. I'll have to see if this doesn't result in a too big memory footprint.
