### ISSUE TITLE
Where is the scannet_v2_val.txt

### ISSUE THREAD

**Issue by Violetit** [HuguesTHOMAS/KPConv#63]
Hi, @HuguesTHOMAS 
Thank you for sharing the code, I want to utilize the data preparation code about Scannet.
 In the line [155] (https://github.com/HuguesTHOMAS/KPConv/blob/11a1d757e9fe273e34aecf0c797170dd458be727/datasets/Scannet.py#L155) , I can not find the `.txt` file.  
Could you help me with this issue?
Thank you very much!

**Comment by HuguesTHOMAS** [comment]
Hi @Violetit,

I have not used this dataset for a while, I think this is [this file](https://github.com/ScanNet/ScanNet/blob/master/Tasks/Benchmark/scannetv2_val.txt). I don't know why the file name is not the same in my implementation.

Best,
Hugues
