### ISSUE TITLE
cuda=8.0,can't find the tf.batch_gather

### ISSUE THREAD

**Issue by csuzhuzhuxia** [HuguesTHOMAS/KPConv#65]
cuda=8.0
tensorflow==1.4.0
I find the error
```
AttributeError: module 'tensorflow' has no attribute 'batch_gather'
```
I only can find  two similar function:tf.gather_nd and tf.gather,how to use them to replace the batch_gather?
thank you!

**Comment by HuguesTHOMAS** [comment]
Hi, 

tf 1.4.0 is a very old version, tf.batch_gather was not implemented yet, and tf.gather had no attribute "batch_dim" at this time. SO you would have to implement your own function which would be very difficult.

I can only advise you to update tensorflow to a later version.

Best,
Hugues
