### ISSUE TITLE
random ball sampling ? 

### ISSUE THREAD

**Issue by antonyvan** [HuguesTHOMAS/KPConv#66]
Hi, Hugues,
Thanks you for your excellent work.  I got a question regarding the data preparation. 
Do you randomly pick sphere for both training and testing ?  I see you are using the same data preparation code for both ?  Is this the reason why you got about 2 percent boost in testing , right ? 

Thanks a lot

**Comment by HuguesTHOMAS** [comment]
Hi @antonyvan,

Actually the spheres for training and test are chosen with what I called "potential strategy". You can see how that works in the batch_gen functions. This strategy uses potential to make the random sampling invariant to density variations. The basic idea is that every point has a potential (a scalar value initiated randomly) and everytime we need to pick a new sphere, we choose the point with the lowest potential as the center. Then we increment the potential of all sphere points and so on.

I hope that helps.

Best,
Hugues

**Comment by antonyvan** [comment]
Thanks Hugues,  This really helps.

________________________________
