### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: targets[872] is out of range

### ISSUE THREAD

**Issue by camelliawb** [HuguesTHOMAS/KPConv#67]
Thanks for your great work and nice code.
I met some problems when I use the project on my own dataset,I have no idea how to deal with it.
I hope you can help me.
Caught a NaN error :
3
targets[872] is out of range
         [[node results/in_top_k/InTopKV2 (defined at /home/sanwei/下载/beifen/KPConvmy/utils/trainer.py:191)  = InTopKV2[T=DT_INT32, _device="/job:localhost/replica/task:0/device:CPU:0"](KernelPointNetwork/softmax/GatherNd, IteratorGetNext:24, optimizer/gradients/range_9/delta)]]
name: "results/in_top_k/InTopKV2"
op: "InTopKV2"
input: "KernelPointNetwork/softmax/GatherNd"
input: "IteratorGetNext:24"
input: "results/in_top_k/InTopKV2/k"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}

results/in_top_k/InTopKV2
['KernelPointNetwork/softmax/GatherNd:0', 'IteratorGetNext:24', 'results/in_top_k/InTopKV2/k:0']
['results/in_top_k/InTopKV2:0']
Traceback (most recent call last):
  File "/home/sanwei/anaconda3/envs/KPconv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/sanwei/anaconda3/envs/KPconv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/sanwei/anaconda3/envs/KPconv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: targets[872] is out of range
         [[{{node results/in_top_k/InTopKV2}} = InTopKV2[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](KernelPointNetwork/softmax/GatherNd, IteratorGetNext:24, optimizer/gradients/range_9/delta)]]

**Comment by HuguesTHOMAS** [comment]
It seems that you have a problem in your data preparation, and as a result, one of the operation of the network failed. The operation that fails is "in_top_k" which takes as input the logits and tha labels. So the failure could come form the number of class, wrong shape of labels and logits etc...

The best way to find out why is to use tf.print op to debug the problem.

Let me know if you find the source of the error or if you have more information with tf.print, but still dont understand what happens.

Best,
Hugues

**Comment by fuluoloo** [comment]
Thanks for your reply!I have already solved this problem,and I have another question that do you use Data Augmentation in this project?If yes where are they?

**Comment by fuluoloo** [comment]
> It seems that you have a problem in your data preparation, and as a result, one of the operation of the network failed. The operation that fails is "in_top_k" which takes as input the logits and tha labels. So the failure could come form the number of class, wrong shape of labels and logits etc...
> 
> The best way to find out why is to use tf.print op to debug the problem.
> 
> Let me know if you find the source of the error or if you have more information with tf.print, but still dont understand what happens.
> 
> Best,
> Hugues

Thanks for your reply!I have already solved this problem,and I have another question that do you use Data Augmentation in this project?If yes where are they?

**Comment by HuguesTHOMAS** [comment]
Yes I do. YOu can find the data augmentation function here:
https://github.com/HuguesTHOMAS/KPConv/blob/a54f594f613e3f8801f9946ec0f3e3d2ff5f994b/datasets/common.py#L225-L292

**Comment by fuluoloo** [comment]
It's me again.I use ShapeNetPart to run my own dataset,the results are really strange and bad.I checked the input data and labels but found no errors.I don't know where the problem is,can you give me some advice?

**Comment by fuluoloo** [comment]
> Yes I do. You can find the data augmentation function here:
> https://github.com/HuguesTHOMAS/KPConv/blob/a54f594f613e3f8801f9946ec0f3e3d2ff5f994b/datasets/common.py#L225-L292

It's me again.I use ShapeNetPart to run my own dataset,the results are really strange and bad.I checked the input data and labels but found no errors.I don't know where the problem is,can you give me some advice?

**Comment by HuguesTHOMAS** [comment]
It is not really possible for me to help you without knowing anything of your code and data. There could be many reasons for these bad results. In my experience, it often comes from the data preprocessing. I guess my advice could be to ficus on the data, try to display input point clouds and verify yourself that they are like you want.

**Comment by fuluoloo** [comment]
> 如果我不了解您的代码和数据的任何内容，对我来说实际上是不可能的。这些不良结果可能有很多原因。以我的经验，它通常来自数据预处理。我想我的建议可能是关注数据，尝试显示输入点云并验证自己是否像您想要的。

I have already checked the input data and found nothing wrong.My own dataset has one hundred data，is this bad result due to the lack of data?I read the  code about data enhancement but I'm confused about how many data I got after data enhancement.
Sorry to bother you again，looking forward to your reply.

**Comment by fuluoloo** [comment]
> It is not really possible for me to help you without knowing anything of your code and data. There could be many reasons for these bad results. In my experience, it often comes from the data preprocessing. I guess my advice could be to ficus on the data, try to display input point clouds and verify yourself that they are like you want.

I have already checked the input data and found nothing wrong.My own dataset has one hundred data，is this bad result due to the lack of data?I read the code about data enhancement but I'm confused about how many data I got after data enhancement.
Sorry to bother you again，looking forward to your reply.

**Comment by HuguesTHOMAS** [comment]
The bad results could come from the lack of data, which would lead the network to overfit. To answer your question, the data augmentation is random, so you still have the same number of data but hey are randomly scaled and rotated everytime you feed them to the network.

In my opinion there could be something messed up in the way you feed the data to the network. Have you displayed examples of data before and after augmentation, and right before they are fed to the network?
