### ISSUE TITLE
 Classification results on ModelNet40 of DGCNN

### ISSUE THREAD

**Issue by Gaozhongpai** [HuguesTHOMAS/KPConv#68]
I have a question about the classification results on ModelNet40 of DGCNN [43]. In the original paper DGCNN [43], Table 2 shows the result of 93.5. In the paper of KPConv, Table 1 shows 92.2 for DGCNN. May I ask how the authors got the result of 92.2 for DGCNN and why it is lower than the original paper?

**Comment by HuguesTHOMAS** [comment]
Hi @Gaozhongpai,

At the time of submission, this was the score obtain by DGCNN. On Arxiv, you can see this score by checking the v1 of DGCNN paper.

Best,
Hugues
