### ISSUE TITLE
Question about train-validation split

### ISSUE THREAD

**Issue by Esteban-25** [HuguesTHOMAS/KPConv#72]
Hi, thank you very much for your work. 
Mine is just a question for clarification: can you please explain to me how exactly the train-validation split is done? I cannot really understand what is meant in this line 
https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/datasets/Semantic3D.py#L145
Many thanks!

**Comment by HuguesTHOMAS** [comment]
Hi @Esteban-25,

I just separate the training dataset in 6 groups of scenes. Each scene is assigned a group idx between 0 and 5. 

Then you can choose the group used for validation with:
https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/datasets/Semantic3D.py#L146

**Comment by Esteban-25** [comment]
Thank you very much for such a quick answer. 

Perhaps dumb question, but is there a reason for it be 15 elements in that array? I am just trying to use a custom dataset that has more training files than Semantic3D and am having troubles with running the training file. The error I get leads me back to the line I sent and was wondering if the number of training files had sth to do with the number of elements in the self.all_splits array.

**Comment by HuguesTHOMAS** [comment]
There are 15 training files in Semantic3D, so 15 elements in this array. Just add as many elements as necessary to this array, according to the number of training files you have

**Comment by Esteban-25** [comment]
Thanks a lot for the help.
