### ISSUE TITLE
IndexError: index 3 is out of bounds for axis 0 with size 3

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#73]
Thanks for your great work,after I have trained, I run python  visualize_features.py,I meet this problem:

/KPConv-master2/utils/visualizer.py", line 220, in top_relu_activations
    l = np.argmax(np.bincount(labels[b]))
IndexError: index 3 is out of bounds for axis 0 with size 3
can you help me?looking forward to your reply.

**Comment by HuguesTHOMAS** [comment]
Hi @longmalongma,

this is strange... Something seems to be wrong with the labels. Did you use your own dataset? is it segmentation or classification?

**Comment by longmalongma** [comment]
> Hi @longmalongma,
> 
> this is strange... Something seems to be wrong with the labels. Did you use your own dataset? is it segmentation or classification?

Thanks for your reply,I use modelnet40 according your gｕiｄａｎｃe and do  not change anything.It is classification and i want to ｖisual feature leraned during trian your network on modelnet40

**Comment by HuguesTHOMAS** [comment]
Then there is a problem with the name of the dataset. The visualiser code should not reach line 220, but instead line 218. As you can see below.
https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/utils/visualizer.py#L217-L220

Just print `model.config.dataset` before line 217.

If I am correct you should see `ModelNet40`. In that case, modify line 217 by changing the name `ModelNet40_classif`, by `ModelNet40`.

**Comment by longmalongma** [comment]
> Then there is a problem with the name of the dataset. The visualiser code should not reach line 220, but instead line 218. As you can see below.
> 
> https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/utils/visualizer.py#L217-L220
> 
> Just print `model.config.dataset` before line 217.
> 
> If I am correct you should see `ModelNet40`. In that case, modify line 217 by changing the name `ModelNet40_classif`, by `ModelNet40`.
Thanks for your help,I have solved this problem according to your guidance.
What do the ｐｏｉｎｔ of different colors represent in the feature picture? Can you visualize the features of each convolutional layer of a point cloud model?
![snapshot](https://user-images.githubusercontent.com/40291722/80985114-5c50ea00-8e61-11ea-9209-c209ddabcad9.png)

**Comment by HuguesTHOMAS** [comment]
Red means high feature activations and blue low feature activations. Use `chosen_relu` below to choose which layer you want to visualize.
https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/visualize_features.py#L229-L234

More details are in the [visualization guide](https://github.com/HuguesTHOMAS/KPConv/blob/master/doc/visualization_guide.md) and the [KPConv article](https://arxiv.org/abs/1904.08889)

**Comment by longmalongma** [comment]
> Red means high feature activations and blue low feature activations. Use `chosen_relu` below to choose which layer you want to visualize.
> 
> https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/visualize_features.py#L229-L234
> 
> More details are in the [visualization guide](https://github.com/HuguesTHOMAS/KPConv/blob/master/doc/visualization_guide.md) and the [KPConv article](https://arxiv.org/abs/1904.08889

I got it,after  I run python visualize_features.py,I get some ply files,and I use meshlab to show it,I find all points are same color in a ply  file,I thinks there is something wrong with saving the feature.

**Comment by longmalongma** [comment]
> Red means high feature activations and blue low feature activations. Use `chosen_relu` below to choose which layer you want to visualize.
> 
> https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/visualize_features.py#L229-L234
> 
> More details are in the [visualization guide](https://github.com/HuguesTHOMAS/KPConv/blob/master/doc/visualization_guide.md) and the [KPConv article](https://arxiv.org/abs/1904.08889)

     

I got it,after I run python visualize_features.py,I get some ply files,and I use meshlab to show it,I find all points are same color in a ply file,I thinks there is something wrong with saving the feature.
