### ISSUE TITLE
all points are same color in a ply file of feature

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#74]
Thanks for your great work.After I run python visualize_features.py,I get some ply files,and I use meshlab to show it,I find all points are same color in a ply file of feature,I thinks there is something wrong with saving the feature.I run code according to your guidance and I never change anything,can your help me?

**Comment by longmalongma** [comment]
> Thanks for your great work.After I run python visualize_features.py,I get some ply files,and I use meshlab to show it,I find all points are same color in a ply file of feature,I thinks there is something wrong with saving the feature.I run code according to your guidance and I never change anything,can your help me?

looking forward to your reply.

**Comment by HuguesTHOMAS** [comment]
The ply files are saved here:
https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/utils/visualizer.py#L314-L317
Try to print the `influence` and `responses` arrays. If you can see values in these arrays, then they are saved under these names. I usually load point cloud with CloudCompare.

**Comment by longmalongma** [comment]
> The ply files are saved here:
> 
> https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/utils/visualizer.py#L314-L317
> 
> Try to print the `influence` and `responses` arrays. If you can see values in these arrays, then they are saved under these names. I usually load point cloud with CloudCompare.

Ｔhank you for your reply. It is strange that when I run python visualize_features.py, the points in the picture are of different colors, but the points in the saved ply file are all the same color

**Comment by longmalongma** [comment]
> The ply files are saved here:
> 
> https://github.com/HuguesTHOMAS/KPConv/blob/132fdc628fb4850548e931c8b02c6325e7cac85e/utils/visualizer.py#L314-L317
> 
> Try to print the `influence` and `responses` arrays. If you can see values in these arrays, then they are saved under these names. I usually load point cloud with CloudCompare.

when I run python visualize_features.py,ｃan we sample the visualized features?

**Comment by HuguesTHOMAS** [comment]
Have you checked the ply file header? If the points in the picture are of different colors, then the ply files should contain the scalar fields. You might be loading the point cloud in the wrong way with meshlab.

**Comment by longmalongma** [comment]
> Have you checked the ply file header? If the points in the picture are of different colors, then the ply files should contain the scalar fields. You might be loading the point cloud in the wrong way with meshlab.
Thank you very much,I want to visualize the features extracted by the convolution layer in my model. Do you have any good ｓuggestions?
