### ISSUE TITLE
ｈｏｗ to visualize the features extracted by the convolution layer in my extracted by the convolution layer in my own model. model. 

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#75]
Thanks for your interesting work,I want to visualize the features extracted by the convolution layer in my own model. Do you have any good ｓuggestions?

**Comment by HuguesTHOMAS** [comment]
I don't understand your question. There is a `visualize_features.py`. Just use that. If you need to visualize features on a new model that you implemented yourself. Implement a new visualizing script, you can take inspiration form `visualizer.py`

**Comment by longmalongma** [comment]
> I don't understand your question. There is a `visualize_features.py`. Just use that. If you need to visualize features on a new model that you implemented yourself. Implement a new visualizing script, you can take inspiration form `visualizer.py`

Thanks for your reply.
