### ISSUE TITLE
What is the inference time to process single poiintcloud on semamtic kittI?

### ISSUE THREAD

**Issue by chowkamlee81** [HuguesTHOMAS/KPConv#80]
What is the inference time to process single poiintcloud on semamtic kittI?

**Comment by HuguesTHOMAS** [comment]
Hi @chowkamlee81,

It depends on so many things, the parameters you are using, your setup (CPU/GPU)... I would say in my experiments it runs between 0.5 and 10 fps.

**Comment by xmyqsh** [comment]
@chowkamlee81 
How many points are there in terms of 10fps?

**Comment by HuguesTHOMAS** [comment]
@xmyqsh, 10 fps quite fast for such a complicated task, ad the need depends on your application. But KPConv is a generic point cloud classification algorithm, it is not made to be a fast real time lidar classification tool.

In any case, if you want a method that achieve state of the art classification performances at more than 10fps, you cannot use any generic method as is, you will need a specific approach with implementation tricks, C++ and CUDA optimization. It becomes an engineering problem more than a research problem.

This repo is meant to be a research project, it was coded only by me and is surely far from optimized for realtime applications

**Comment by xmyqsh** [comment]
Hmm，KPConv could be a module/block in other tasks, not limit to classification/segmentation.

**Comment by HuguesTHOMAS** [comment]
Exactly, this is a module that can be adapted through its parameters to fit any task. This is why the fps that it has right now has no real value, because it completely depends on the the task you are using KPConv for.
