### ISSUE TITLE
python3 training_S3DIS.py - data processing

### ISSUE THREAD

**Issue by juzi-dj** [HuguesTHOMAS/KPConv#82]
Hi, thanks for your work. I have encountered some problems and may need your help, thank you. When running python3 training_S3DIS.py and processing the S3DIS data set to the third room of Area_5, it appears
   File "training_S3DIS.py", line 202, in <module>
     dataset = S3DISDataset(config.input_threads)
   File "/home/disk1/dj/downloads/KPConv-master/datasets/S3DIS.py", line 152, in __init__
     self.prepare_S3DIS_ply()
   File "/home/disk1/dj/downloads/KPConv-master/datasets/S3DIS.py", line 203, in prepare_S3DIS_ply
     object_data = np.array([[float(x) for x in line.split()] for line in f])
   File "/home/disk1/dj/downloads/KPConv-master/datasets/S3DIS.py", line 203, in <listcomp>
     object_data = np.array([[float(x) for x in line.split()] for line in f])
   File "/home/disk1/dj/downloads/KPConv-master/datasets/S3DIS.py", line 203, in <listcomp>
     object_data = np.array([[float(x) for x in line.split()] for line in f])
ValueError: could not convert string to float: '185\x00187'

**Comment by HuguesTHOMAS** [comment]
Hi @juzi-dj,

I remember having seen this error before. I think it was because one of the file of S3DIS dataset was corrupted. To find it, I printed the name of the object file just before line 203 in S3DIS.py, and then the line index where this error happens. And I just corrected the file myself

**Comment by juzi-dj** [comment]
Thank you for your reply, I will check again.

**Comment by wlw-nwafu** [comment]
> 感谢您的答复，我将再次检查。
Hello, I have the same problem as you. Have you solved it?

**Comment by antonyvan** [comment]
This error may be caused by copy or download.     the error is that that line has < >  you can print all line number 
for example : 
import numpy as np
object_file = "S3DIS/Area_5/office_19/Annotations/ceiling_1.txt"

print(object_file)
with open(object_file, 'r') as f:
    for idx, line in enumerate(f):
        print(idx)
        for x in line.split():
            data  = np.array([float(x)])
