### ISSUE TITLE
What the difference between class average IoU (mcIoU) and instance average IoU (mIoU) for ShapeNetPart dataset?

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#86]
Hi,thanks for your great work, can you tell me what the difference between class average IoU (mcIoU) and instance average IoU (mIoU) for ShapeNetPart dataset?How to distinguish them in the codes?

**Comment by HuguesTHOMAS** [comment]
First we compute IoU for all instance object. The instance mIoU is the average off all instance IoU. To get the class mcIoU, we first get the the IoU for each class (see Table 5 in paper supplementatry). THe mcIoU is the average of all the class IoU.

You can look a the function `compare_convergences_multisegment` in `plot_convergence.py` where both metrics are computed:
https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/plot_convergence.py#L352

**Comment by longmalongma** [comment]
> First we compute IoU for all instance object. The instance mIoU is the average off all instance IoU. To get the class mcIoU, we first get the the IoU for each class (see Table 5 in paper supplementatry). THe mcIoU is the average of all the class IoU.
> 
> You can look a the function `compare_convergences_multisegment` in `plot_convergence.py` where both metrics are computed:
> 
> https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/plot_convergence.py#L352

Thanks!
