### ISSUE TITLE
how to print out the parameters and FLOPs of every convolutional layer and fully connected layer of the whole neural network

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#87]
A question has been bothering me for a long time, I would like to ask you, do you know how to print out the parameters and FLOPs of every convolutional layer and fully connected layer of the whole neural network?looking forward to your reply.

**Comment by HuguesTHOMAS** [comment]
I know how to print out every layer of the network. Look a these commented line in trainer.py

https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/utils/trainer.py#L64-L80

Unfortunately I never printed out the realtime FLOPS of the network so you are going to figure out this one by yourself
