### ISSUE TITLE
S3DIS visualization

### ISSUE THREAD

**Issue by juzi-dj** [HuguesTHOMAS/KPConv#88]
I have encountered some problems again. May I ask if you have visualized the S3DIS dataset? Is it convenient to provide some processing ideas? Thank you very much!

**Comment by HuguesTHOMAS** [comment]
I don't understand your question. Do you want to visualize the pointclouds of each area? 
If its your problem, I usually visualize the pointcloud with [CloudCompare](https://www.danielgm.net/cc/). just open the .ply files with this software

**Comment by juzi-dj** [comment]
Thank you very much for your reply. Sorry, I will now describe my problem again. Will new .ply files or other files （the pointclouds of each area）with predicted tags  be generated after running python training_S3DIS.py? ? ? I want to put these files with predicted tags into cloudcompare for visualization, and then compare it with original .ply files （the pointclouds of each area）with real tags （groundtruth）.

This may require me to run it  to get the results, but for some reason I encountered some difficulties, so I want to know the difficulty of this visualization in advance. thank you!

**Comment by HuguesTHOMAS** [comment]
When running `training_S3DIS.py`, prediction files (.ply) are generated every 50 epochs and are located in the results folder. THese files already contain the predictions AND the groundtruth classes. SO you can just put them in CC to see the results.
