### ISSUE TITLE
How to visualize the segmentation results on the Semantic3D dataset?

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#89]
Hi,How do I visualize the segmentation results on the Semantic3D dataset?

**Comment by HuguesTHOMAS** [comment]
Same as S3DIS, some .ply file are saved in the log folder. Just search for them in the folder called `val_preds`

I don't save all the frames as .ply because it would be too big. Only one frame every 20 frames is saved or something.
