### ISSUE TITLE
question about the results of s3dis

### ISSUE THREAD

**Issue by fullcyxuc** [HuguesTHOMAS/KPConv#92]
hi, thanks for your excellent work! I have a question about the result of experiment for s3dis. In your paper, the table 2 shows that Pointnet's mIoU in S3DIS is 41.1 however i find that its 47.71 in Pointnet' paper. I wonder why they are different. It would be appreciated it if you could give me a detailed response.

**Comment by HuguesTHOMAS** [comment]
Hi @fullcyxuc, 

Thanks for your interest in this work. In the paper we report the results computed with Area5 as test set, which is what the authors of S3DIS dataset advised in their own paper. In the original PointNet paper, the results are computed in a *k-fold* validation scheme (Each area is used as test set in a separate experiment and then the results are averaged over the whole dataset).

You can look at the supplementary material of our paper where we report the detailed results on S3DIS in both setups. I hope you appreciated this detailed response.

Best,
Hugues

**Comment by fullcyxuc** [comment]
> Hi @fullcyxuc,
> 
> Thanks for your interest in this work. In the paper we report the results computed with Area5 as test set, which is what the authors of S3DIS dataset advised in their own paper. In the original PointNet paper, the results are computed in a _k-fold_ validation scheme (Each area is used as test set in a separate experiment and then the results are averaged over the whole dataset).
> 
> You can look at the supplementary material of our paper where we report the detailed results on S3DIS in both setups. I hope you appreciated this detailed response.
> 
> Best,
> Hugues

I see, thank you for your reply
