### ISSUE TITLE
Mayavi configuration

### ISSUE THREAD

**Issue by jspruitt** [HuguesTHOMAS/KPConv#93]
I'm am struggling to get mayavi to work with my configuration(ubuntu server and jupyter notebook). What configuration did you use?

**Comment by zhouhao957** [comment]
If you use pycharm
pycharm-->file-->settings-->project:xxx-->project interpreter-->'+'-------------Search for what you need

**Comment by HuguesTHOMAS** [comment]
I am not sure Mayavi works well with Jupyter and ssh. For more details, you can try to have a look at [this page](https://docs.enthought.com/mayavi/mayavi/tips.html).
