### ISSUE TITLE
How to change S3DIS testing area(semantic segmentation)?

### ISSUE THREAD

**Issue by suan0365006** [HuguesTHOMAS/KPConv#95]
Dear author,
Thank you very much for sharing this great work. 

I am a beginner on semantic segmentation, I have a little question for S3DIS testing, can I change the test area?

For example, the default seem to use Area 1, Area 2, Area 3, Area 4, Area 6 as the training sample, and Area 5 as the test area.

Now, I want to change the training area to Area 2, Area 3, Area 4, ,Area 5, Area 6, and use Area 1 as the testing area.

In training_S3DIS.py and datasets.S3DIS.py I seem to be unable to find the parameters that can be changed, this may be caused by my carelessness.

Thank you again!
I will close my discussion after this problem is resolved.

Best Regards.

**Comment by HuguesTHOMAS** [comment]
Hi @suan0365006,

You can find what you need here:

https://github.com/HuguesTHOMAS/KPConv/blob/07861d8e40244c20ede5a362052e01f61dcc012a/datasets/S3DIS.py#L140-L143

The parameter `self.all_splits` gives a "split" index to all the clouds and the parameter `self.validation_split` lets you choose which  split is used for validation. SO in you case you just have to set `self.validation_split = 0`

Best,
Hugues

**Comment by suan0365006** [comment]
Hi @HuguesTHOMAS ,

I got it!
Thank you so much for responding to my email.

Warm Regards.
