### ISSUE TITLE
How to download scannet dataset more conveniently?

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#96]
How to download scannet dataset more conveniently? The command line download provided by the official website is particularly slow.

**Comment by HuguesTHOMAS** [comment]
@longmalongma,

I agree but I did not find another way. I used this command line and let it run through the night.

**Comment by longmalongma** [comment]
> @longmalongma,
> 
> I agree but I did not find another way. I used this command line and let it run through the night.

Thanks!

**Comment by longmalongma** [comment]
Thanks for your relpy. What is the specific command you use to download the Scannet dataset?I want to download only the data needed for training and testing. Downloading the entire data set is too big

**Comment by HuguesTHOMAS** [comment]
It was a long time ago, I have to say I don't remember exactly. I definitely avoided downloading the images. You need the scans and the object labels I think
