### ISSUE TITLE
What are the FLOPs of your segmentation model in the semantic segmentation task on the s3dis dataset?

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#98]
What are the FLOPs of your segmentation model in the semantic segmentation task on the s3dis dataset?

**Comment by HuguesTHOMAS** [comment]
I never measured the FLOPS of my models, but I think there are tools to do it with Tensorflow, or even in the PyTorch version if you want to.

You have to notice though that the FLOPS depend on a lot of the parameters, including the architecture, the first_subsampling_dl, the convolution density parameters, the number of kernel points, etc... As explained in the paper, our design is very flexible in that sense.

Best,
Hugues
