### ISSUE TITLE
Can not test on modelnet40

### ISSUE THREAD

**Issue by longmalongma** [HuguesTHOMAS/KPConv#99]
After I have trained your model on modelnet40,I try to run python3 test_any_model.py,I meet this problem,can you help me?looking forward to your reply.
 (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "test_any_model.py", line 268, in <module>
    log_config.load(log)
  File "/media/lab601/mycode/KPConv-master/utils/config.py", line 185, in load
    if line_info[2] == 'None':
IndexError: list index out of range

**Comment by HuguesTHOMAS** [comment]
The configuration file (`your_log_path/parameters.txt`) seems corrupted, can you check it?

Best,
Hugues
